/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import shop.GUI.Login;
import shop.data_source_pkg.DataSourc;
import shop.GUI.Main_Frame;

/**
 *
 * @author ahmed
 */
public class StartWindow extends javax.swing.JFrame {

    /**
     * Creates new form StratWindow
     */
 static   DataSourc d;
 Image StartImage;
  Image LoginImage;
  
 static Main_Frame main_frame;
    public StartWindow() {
      
        try
{
    StartImage = ImageIO.read(new shop.recources_pkg.ResourceLoader().getStart_image());
    LoginImage = ImageIO.read(new shop.recources_pkg.ResourceLoader().getLogIn_image());


}catch(IOException ex){


}
        initComponents();
     this.connecting_PB.setVisible(false);

    }
    String NormalizeinArabic(String str) {

        char[] arabicChars = {'٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'};
        if (str == null) {
            return str;
        }
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            if (Character.isDigit(str.charAt(i))) {
                builder.append(arabicChars[(int) (str.charAt(i)) - 48]);
            } else {
                builder.append(str.charAt(i));
            }
        }
//        System.out.println("Number in English : " + str);
//        System.out.println("Number In Arabic : " + builder.toString());
        return builder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connecting_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new shop.test.ImagePanel(StartImage);
        monitor_label = new javax.swing.JLabel();
        connecting_PB = new javax.swing.JProgressBar();
        login_panel = new shop.test.ImagePanel(LoginImage);
        userName_TF = new javax.swing.JTextField();
        password_TF = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ok_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        warnning_label = new javax.swing.JLabel();
        firdage_CB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        connecting_panel.setForeground(new java.awt.Color(103, 21, 17));

        javax.swing.GroupLayout connecting_panelLayout = new javax.swing.GroupLayout(connecting_panel);
        connecting_panel.setLayout(connecting_panelLayout);
        connecting_panelLayout.setHorizontalGroup(
            connecting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        connecting_panelLayout.setVerticalGroup(
            connecting_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(500, 150));
        setSize(new java.awt.Dimension(300, 200));
        setType(java.awt.Window.Type.UTILITY);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setPreferredSize(new java.awt.Dimension(395, 490));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(300, 600));

        monitor_label.setForeground(new java.awt.Color(237, 222, 3));
        monitor_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        monitor_label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        connecting_PB.setToolTipText("جاري التحميل ");
        connecting_PB.setOpaque(true);
        connecting_PB.setStringPainted(true);
        connecting_PB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                connecting_PBStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitor_label, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(connecting_PB, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(528, Short.MAX_VALUE)
                .addComponent(monitor_label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connecting_PB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel2.add(jPanel4, "card2");

        login_panel.setPreferredSize(new java.awt.Dimension(395, 490));
        login_panel.setLayout(null);

        userName_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        userName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userName_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_TFActionPerformed(evt);
            }
        });
        login_panel.add(userName_TF);
        userName_TF.setBounds(50, 200, 180, 30);

        password_TF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        login_panel.add(password_TF);
        password_TF.setBounds(50, 240, 180, 32);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("رقم الثلاجة");
        login_panel.add(jLabel3);
        jLabel3.setBounds(230, 160, 85, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("كلمة المرور");
        login_panel.add(jLabel2);
        jLabel2.setBounds(230, 240, 85, 30);

        ok_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ok_btn.setText("تم");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });
        login_panel.add(ok_btn);
        ok_btn.setBounds(50, 300, 60, 40);

        cancel_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancel_btn.setText("إلغاء");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        login_panel.add(cancel_btn);
        cancel_btn.setBounds(130, 300, 60, 40);

        warnning_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        warnning_label.setForeground(new java.awt.Color(255, 255, 0));
        warnning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_panel.add(warnning_label);
        warnning_label.setBounds(20, 270, 370, 22);

        firdage_CB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firdage_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { NormalizeinArabic("محل 18 "),NormalizeinArabic( "محل 21 ") }));
        login_panel.add(firdage_CB);
        firdage_CB.setBounds(50, 160, 180, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("اسم المستخدم");
        login_panel.add(jLabel4);
        jLabel4.setBounds(230, 200, 85, 30);

        jPanel2.add(login_panel, "login_card");

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
         // TODO add your handling code here:
        String userName=userName_TF.getText();
        char [] pass=password_TF.getPassword();
        
     if(!d.isUniqueInstance()){d.logout();}
      String passeord="";
        for(int i=0;i<pass.length;i++){
      passeord+=pass[i];
      
      }
        if(userName.isEmpty()){
           this.warnning_label.setText("يجب إدخال اسم المستخدم");
        }
        else if(passeord.isEmpty()){
          this.warnning_label.setText("يجب إدخال كلمة المرور");
        }
        if (d.authenticateUser(userName, passeord)) {
            
                           CardLayout c = (CardLayout) jPanel2.getLayout();
                c.show(jPanel2, "card2");
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                
                 StartWindow.main_frame=new Main_Frame(StartWindow.d,firdage_CB.getSelectedIndex()+1);
                
               main_frame.setVisible(true);
            }
        });
    
                
       //    StartWindow.main_frame=new Main_Frame(StartWindow.d,firdage_CB.getSelectedIndex()+1);
          //  main_frame.firdage_id=firdage_CB.getSelectedIndex()+1;
           
        } else {
            this.warnning_label.setText("كلمة السر خاطئه");
          
        }
     
    
    }//GEN-LAST:event_ok_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:

this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void connecting_PBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_connecting_PBStateChanged
        // TODO add your handling code here:
        int val = connecting_PB.getValue();
        if (val == 50) {
                            CardLayout c = (CardLayout) jPanel2.getLayout();
                c.show(jPanel2, "login_card");
          

        }
        if (val == 100) {
               
               
           this.dispose();
           
           

        }
    }//GEN-LAST:event_connecting_PBStateChanged

    private void userName_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_TFActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
 
    }//GEN-LAST:event_formFocusGained
    public static void fail(int error) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                
                  StartWindow SW =  new StartWindow();
                     SW.setAlwaysOnTop(true);
                    SW.setVisible(true);
                

            }
        });
   
     try {
         Thread.sleep(4000);
                  
                  StartWindow.d=new DataSourc();
                           Thread.sleep(1000);

                  
                   
                  
                } catch (InterruptedException ex) {
                    d.logout();
                    Logger.getLogger(StartWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
       
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    public static javax.swing.JProgressBar connecting_PB;
    public static javax.swing.JPanel connecting_panel;
    private javax.swing.JComboBox firdage_CB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel login_panel;
    public static javax.swing.JLabel monitor_label;
    private javax.swing.JButton ok_btn;
    private javax.swing.JPasswordField password_TF;
    private javax.swing.JTextField userName_TF;
    private javax.swing.JLabel warnning_label;
    // End of variables declaration//GEN-END:variables
}
