/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archive_pkg;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import javax.swing.JFrame;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author Ahmed
 */
public class Archive extends javax.swing.JPanel {

    /**
     * Creates new form Archive
     */
    DataSourc data_source;
    JFrame myFrame;
    Map<String,Integer>seasonsMap;
    CustomersARC customers_tab;
    SellersARC sellers_tab;
    ExpensasARC expanses_tab;
    OrdersARC orders_tab;
    InventoryARC inventory_tab;
    KTabsARC K_TabsARC;
    
    boolean fillingMode;
    public Archive(JFrame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        seasonsMap=new HashMap<>();
        initComponents();
        intiatePage();
    }
    void intiatePage(){
    fillSeasons();
    if(season_CB.getItemCount()>0){
    String selectedItem=season_CB.getSelectedItem().toString();
    int seasonID=seasonsMap.get(selectedItem);
    int fridageNumber=fridageNumber_CB.getSelectedIndex()+1;
    customers_tab=new CustomersARC(myFrame, data_source, seasonID, fridageNumber);
    sellers_tab=new SellersARC(myFrame, data_source, seasonID, fridageNumber);
    expanses_tab=new ExpensasARC(myFrame, data_source, seasonID);
    orders_tab=new OrdersARC(myFrame, data_source, seasonID, fridageNumber);
    inventory_tab=new InventoryARC(myFrame, data_source, seasonID);
    K_TabsARC=new KTabsARC(myFrame, data_source, seasonID);
    
    
    DailySales_tab.add(sellers_tab);
    Expanses_Tab.add(expanses_tab);
    Inventory_Tab.add(inventory_tab);
    Customers_Tab.add(customers_tab);
    Orders_Tab.add(orders_tab);
    Kareem_Tab.add(K_TabsARC);
    
      fillingMode=false;
    season_CB.setSelectedIndex(season_CB.getItemCount()-1);
    }
    
    
    }
    
    
    void refrishPage(){
    String selectedItem=season_CB.getSelectedItem().toString();
    int seasonID=seasonsMap.get(selectedItem);
    int fridageNumber=fridageNumber_CB.getSelectedIndex()+1;
    
    expanses_tab.refrishPage(seasonID, fridageNumber);
    expanses_tab.refrishPage(seasonID, fridageNumber);
    customers_tab.refrishPage(seasonID, fridageNumber);
    inventory_tab.refrishPage(seasonID);
    orders_tab.refrishPage(seasonID, fridageNumber);
    sellers_tab.refrishPage(seasonID, fridageNumber);
    K_TabsARC.refrish(seasonID);
    
    }
    void fillSeasons(){
    
   this.seasonsMap=data_source.getSeasons();
    
    fillingMode=true;
    season_CB.removeAllItems();
    Iterator it = seasonsMap.entrySet().iterator();
    while (it.hasNext()) {
        Map.Entry pair = (Map.Entry)it.next();
        season_CB.addItem(pair.getKey());
       // it.remove(); // avoids a ConcurrentModificationException
        
    }
  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        month_CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        day_CB = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        fridageNumber_CB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        season_CB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DailySales_tab = new javax.swing.JPanel();
        Customers_Tab = new javax.swing.JPanel();
        Expanses_Tab = new javax.swing.JPanel();
        Orders_Tab = new javax.swing.JPanel();
        Inventory_Tab = new javax.swing.JPanel();
        Kareem_Tab = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الشهر");

        month_CB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        month_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        month_CB.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("اليوم");

        day_CB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        day_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        day_CB.setPreferredSize(new java.awt.Dimension(75, 30));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 204), 2, true));

        fridageNumber_CB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fridageNumber_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ثلاجة 18 ", "ثلاجة 21 " }));
        fridageNumber_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridageNumber_CBActionPerformed(evt);
            }
        });
        jPanel1.add(fridageNumber_CB);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم الثلاجة");
        jPanel1.add(jLabel4);

        season_CB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        season_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        season_CB.setPreferredSize(new java.awt.Dimension(250, 30));
        season_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                season_CBActionPerformed(evt);
            }
        });
        jPanel1.add(season_CB);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الموسم");
        jPanel1.add(jLabel3);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        DailySales_tab.setLayout(new javax.swing.OverlayLayout(DailySales_tab));
        jTabbedPane1.addTab("المبيع", DailySales_tab);

        Customers_Tab.setLayout(new javax.swing.OverlayLayout(Customers_Tab));
        jTabbedPane1.addTab("العملاء", Customers_Tab);

        Expanses_Tab.setLayout(new javax.swing.OverlayLayout(Expanses_Tab));
        jTabbedPane1.addTab("التحصيل", Expanses_Tab);

        Orders_Tab.setLayout(new javax.swing.OverlayLayout(Orders_Tab));
        jTabbedPane1.addTab("الفواتير", Orders_Tab);

        Inventory_Tab.setLayout(new javax.swing.OverlayLayout(Inventory_Tab));
        jTabbedPane1.addTab("الجرد", Inventory_Tab);

        Kareem_Tab.setLayout(new javax.swing.OverlayLayout(Kareem_Tab));
        jTabbedPane1.addTab("كريم", Kareem_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("العملاء");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void season_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_season_CBActionPerformed
         // TODO add your handling code here:
if(!fillingMode){


refrishPage();




}

    }//GEN-LAST:event_season_CBActionPerformed

    private void fridageNumber_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridageNumber_CBActionPerformed
        // TODO add your handling code here:
        refrishPage();
    }//GEN-LAST:event_fridageNumber_CBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Customers_Tab;
    private javax.swing.JPanel DailySales_tab;
    private javax.swing.JPanel Expanses_Tab;
    private javax.swing.JPanel Inventory_Tab;
    private javax.swing.JPanel Kareem_Tab;
    private javax.swing.JPanel Orders_Tab;
    private javax.swing.JComboBox day_CB;
    private javax.swing.JComboBox fridageNumber_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox month_CB;
    private javax.swing.JComboBox season_CB;
    // End of variables declaration//GEN-END:variables
}
