/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archive_pkg;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import shop.GUI.Main_Frame;
import shop.GUI_attachement_pkg.PersonName_STF;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author Comu City
 */
public class KChmicalARC extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
      DataSourc data_source;
    JFrame myFrame;
    int seasonID;
    public KChmicalARC(JFrame myFrame,DataSourc data_source,int seasonID) {
         this.data_source=data_source;
        this.myFrame=myFrame;
        this.seasonID=seasonID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        shopPaid_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        KPaid_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchCont_TF = new javax.swing.JButton();
        contractorName_TF = new PersonName_STF(myFrame, "K_S", data_source);
        jLabel3 = new javax.swing.JLabel();
        all_RB = new javax.swing.JRadioButton();
        shop_RB = new javax.swing.JRadioButton();
        K_RB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChemicalSupplierAcccount_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ShopTotal_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ktotal_TF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allContractors_table = new javax.swing.JTable();

        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(900);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true), "البحث", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        shopPaid_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shopPaid_TF.setForeground(new java.awt.Color(255, 51, 0));
        shopPaid_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shopPaid_TF.setEnabled(false);
        shopPaid_TF.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(shopPaid_TF);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setText("المحل");
        jPanel1.add(jLabel2);

        KPaid_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        KPaid_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KPaid_TF.setEnabled(false);
        KPaid_TF.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(KPaid_TF);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("كريم");
        jPanel1.add(jLabel1);

        searchCont_TF.setText("بحث");
        searchCont_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCont_TFActionPerformed(evt);
            }
        });
        jPanel1.add(searchCont_TF);

        contractorName_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        contractorName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        contractorName_TF.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(contractorName_TF);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("اسم المورد:");
        jPanel1.add(jLabel3);

        all_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        all_RB.setSelected(true);
        all_RB.setText("الكل");
        all_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        all_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        all_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_RBActionPerformed(evt);
            }
        });
        jPanel1.add(all_RB);

        shop_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shop_RB.setText("المحل");
        shop_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shop_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        shop_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop_RBActionPerformed(evt);
            }
        });
        jPanel1.add(shop_RB);

        K_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        K_RB.setText("كريم");
        K_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        K_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        K_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_RBActionPerformed(evt);
            }
        });
        jPanel1.add(K_RB);

        ChemicalSupplierAcccount_table.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ChemicalSupplierAcccount_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "البيان", "مدفوع", "المبلغ", "التاريخ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ChemicalSupplierAcccount_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChemicalSupplierAcccount_table.setGridColor(new java.awt.Color(2, 106, 2));
        ChemicalSupplierAcccount_table.setRowHeight(25);
        ChemicalSupplierAcccount_table.setRowMargin(2);
        jScrollPane1.setViewportView(ChemicalSupplierAcccount_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        ShopTotal_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ShopTotal_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShopTotal_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("المحل");

        Ktotal_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ktotal_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ktotal_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("كريم");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Ktotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShopTotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopTotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Ktotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true), "موردبن الكيماوي"));

        allContractors_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        allContractors_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الإجمالي", "اسم المقاول"
            }
        ));
        allContractors_table.setRowHeight(25);
        allContractors_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allContractors_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(allContractors_table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setRightComponent(jPanel4);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void searchCont_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCont_TFActionPerformed
        // TODO add your handling code here:

        searchContAccount(contractorName_TF.getText());
    }//GEN-LAST:event_searchCont_TFActionPerformed

    private void all_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_RBActionPerformed
        // TODO add your handling code here
        if(all_RB.isSelected()){
            int selected=allContractors_table.getSelectedRow();
            if(selected>-1){
                DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
                String   name=dtm.getValueAt(selected, 1).toString();
                searchContAccount(name);

            }

            else if(!contractorName_TF.getText().isEmpty()){
                searchContAccount(contractorName_TF.getText());

            }

        }
    }//GEN-LAST:event_all_RBActionPerformed

    private void shop_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop_RBActionPerformed
        // TODO add your handling code here:
        if(shop_RB.isSelected()){
            int selected=allContractors_table.getSelectedRow();
            if(selected>-1){
                DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
                String   name=dtm.getValueAt(selected, 1).toString();
                searchContAccount(name);

            }

            else if(!contractorName_TF.getText().isEmpty()){
                searchContAccount(contractorName_TF.getText());

            }

        }
    }//GEN-LAST:event_shop_RBActionPerformed

    private void K_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_RBActionPerformed
        // TODO add your handling code here:
        if(K_RB.isSelected()){
            int selected=allContractors_table.getSelectedRow();
            if(selected>-1){
                DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
                String   name=dtm.getValueAt(selected, 1).toString();
                searchContAccount(name);

            }

            else if(!contractorName_TF.getText().isEmpty()){
                searchContAccount(contractorName_TF.getText());

            }

        }
    }//GEN-LAST:event_K_RBActionPerformed

    private void allContractors_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allContractors_tableMouseClicked
        // TODO add your handling code here:
        int index=allContractors_table.getSelectedRow();
        DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
        Vector<Object>row=(Vector<Object>) dtm.getDataVector().get(index);
        String name=(String) row.get(1);
        searchContAccount(name);
    }//GEN-LAST:event_allContractors_tableMouseClicked

    void searchContAccount(String Name){
   
    int sort=2;
    if(K_RB.isSelected()){sort=0;}
    else if(shop_RB.isSelected()){sort=1;}
    Object[][]table =data_source.getContractorAccount(Name, "K_S",sort,seasonID);
        DefaultTableModel dtm=(DefaultTableModel)ChemicalSupplierAcccount_table.getModel();
        dtm.setDataVector(table, contractor_columnsTitle);
    ChemicalSupplierAcccount_table.setModel(dtm);
    setLabourAccount_tableSize();
    double kPaid=data_source.getContractorWithadrawal(Name,0,seasonID);
    double kshop=data_source.getContractorWithadrawal(Name,1,seasonID);
    
    shopPaid_TF.setText(String.valueOf(kshop));
    KPaid_TF.setText(String.valueOf(kPaid));
    }
    void fillAllContractorsTable(){

Vector<Object>data=data_source.getAllContractors("K_S",seasonID);
DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
dtm.setDataVector(data, allcont_column_titles);


}
    void inatiatePage(int seasonID){
 
 double ktotal=data_source.getKTypeWithdrawal("K_S", seasonID, 0);
  double Shoptotal=data_source.getKTypeWithdrawal("K_S", seasonID, 1);

 this.ShopTotal_TF.setText(String.valueOf(Shoptotal));
  this.Ktotal_TF.setText(String.valueOf(ktotal));
 fillAllContractorsTable();
 }
void setLabourAccount_tableSize() {
      // LabourAccount_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < ChemicalSupplierAcccount_table.getColumnModel().getColumnCount(); i++) {
            column = ChemicalSupplierAcccount_table.getColumnModel().getColumn(i);

            switch (i) {
                  case 0:
                    column.setPreferredWidth(250);
                    break;
                  case 1:
                    column.setPreferredWidth(30);
                    break;
                case 2:
                    column.setPreferredWidth(80);
                    break;
                    case 3:
                    column.setPreferredWidth(250);
                    break;

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChemicalSupplierAcccount_table;
    private javax.swing.JTextField KPaid_TF;
    private javax.swing.JRadioButton K_RB;
    private javax.swing.JTextField Ktotal_TF;
    private javax.swing.JTextField ShopTotal_TF;
    private javax.swing.JTable allContractors_table;
    private javax.swing.JRadioButton all_RB;
    private javax.swing.JTextField contractorName_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton searchCont_TF;
    private javax.swing.JTextField shopPaid_TF;
    private javax.swing.JRadioButton shop_RB;
    // End of variables declaration//GEN-END:variables

String []   contractor_columnsTitle=new String [] {
        "البيان", "مدفوع", "المبلغ", "التاريخ"
            };

Vector<Object>allcont_column_titles=new Vector<>(Arrays.asList(
                "الإجمالي", "اسم المورد"
            ));


}
