/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archive_pkg;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import shop.GUI.Main_Frame;
import shop.GUI_attachement_pkg.PersonName_STF;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author Comu City
 */
public class KVariatiesARC extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */  DataSourc data_source;
    JFrame myFrame;
    int seasonID;
    public KVariatiesARC(JFrame myFrame, DataSourc data_source,int seasonID) {
         this.data_source = data_source;
        this.myFrame = myFrame;
        this.seasonID=seasonID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        search_btn = new javax.swing.JButton();
        labourName_TF = new PersonName_STF(myFrame, "K_V", data_source);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        varaiatiesAccount_table = new javax.swing.JTable();
        allContractors_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allContractors_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ShopTotal_TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(900);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true), "البحث", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        search_btn.setText("بحث");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn);

        labourName_TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labourName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        labourName_TF.setMinimumSize(new java.awt.Dimension(6, 30));
        labourName_TF.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(labourName_TF);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("العنوان:");
        jPanel1.add(jLabel3);

        varaiatiesAccount_table.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        varaiatiesAccount_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "البيان", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        varaiatiesAccount_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        varaiatiesAccount_table.setGridColor(new java.awt.Color(2, 106, 2));
        varaiatiesAccount_table.setRowHeight(30);
        varaiatiesAccount_table.setRowMargin(2);
        jScrollPane1.setViewportView(varaiatiesAccount_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        allContractors_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 3, true), "المقاولين"));

        allContractors_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        allContractors_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الإجمالي", "العنوان"
            }
        ));
        allContractors_table.setRowHeight(25);
        allContractors_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allContractors_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(allContractors_table);

        ShopTotal_TF.setFont(new java.awt.Font("B Fantezy", 0, 18)); // NOI18N
        ShopTotal_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShopTotal_TF.setCaretColor(new java.awt.Color(255, 0, 0));
        ShopTotal_TF.setEnabled(false);
        ShopTotal_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("الإجمالي");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ShopTotal_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShopTotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        javax.swing.GroupLayout allContractors_panelLayout = new javax.swing.GroupLayout(allContractors_panel);
        allContractors_panel.setLayout(allContractors_panelLayout);
        allContractors_panelLayout.setHorizontalGroup(
            allContractors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        allContractors_panelLayout.setVerticalGroup(
            allContractors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allContractors_panelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(allContractors_panel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    void inatiatePage(int seasonID) {
       
        double Shoptotal = data_source.getKTypeWithdrawal("K_V", seasonID, 1);

        this.ShopTotal_TF.setText(String.valueOf(Shoptotal));

        fillAllContractorsTable();

    }

    void fillAllContractorsTable() {

        Vector<Object> data = data_source.getAllContractors("K_V",seasonID);
        DefaultTableModel dtm = (DefaultTableModel) allContractors_table.getModel();
        dtm.setDataVector(data, allcont_column_titles);

    }

    void searchContAccount(String Name) {

        Object[][] table = data_source.getContractorAccount(Name, "K_V",2,seasonID);
        DefaultTableModel dtm = (DefaultTableModel) varaiatiesAccount_table.getModel();
        dtm.setDataVector(table, contractor_columnsTitle);
        varaiatiesAccount_table.setModel(dtm);
        setLabourAccount_tableSize();

        double kPaid = data_source.getContractorWithadrawal(Name, 0,seasonID);
        double kshop = data_source.getContractorWithadrawal(Name, 1,seasonID);

    }

    void setLabourAccount_tableSize() {
        // LabourAccount_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < varaiatiesAccount_table.getColumnModel().getColumnCount(); i++) {
            column = varaiatiesAccount_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(250);
                    break;
                case 1:
                    column.setPreferredWidth(80);
                    break;
                case 2:
                    column.setPreferredWidth(100);
                    break;

            }
        }

    }

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        searchContAccount(labourName_TF.getText());
    }//GEN-LAST:event_search_btnActionPerformed

    private void allContractors_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allContractors_tableMouseClicked
        // TODO add your handling code here:
        int index = allContractors_table.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) allContractors_table.getModel();
        Vector<Object> row = (Vector<Object>) dtm.getDataVector().get(index);
        String name = (String) row.get(1);
        searchContAccount(name);
    }//GEN-LAST:event_allContractors_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ShopTotal_TF;
    private javax.swing.JPanel allContractors_panel;
    private javax.swing.JTable allContractors_table;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField labourName_TF;
    private javax.swing.JButton search_btn;
    private javax.swing.JTable varaiatiesAccount_table;
    // End of variables declaration//GEN-END:variables

   String[] contractor_columnsTitle = new String[]{
        "البيان", "المبلغ", "التاريخ"
    };

    Vector<Object> allcont_column_titles = new Vector<>(Arrays.asList(
            "الإجمالي", "العنوان"
    ));

}
