/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author Ahmed
 */
public class Backup_panel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    DataSourc data_source;
    JDialog owner;
    

    public Backup_panel(JDialog owner, DataSourc data_source) {
        this.data_source = data_source;
        this.owner = owner;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backup_FC = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        path_TF = new javax.swing.JTextField();
        browser_btn = new javax.swing.JButton();
        ok_btn = new javax.swing.JButton();
        progBar_panel = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar(0,99);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("المسار:");

        path_TF.setEditable(false);
        path_TF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        path_TF.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        browser_btn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        browser_btn.setText("إختيار");
        browser_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browser_btnActionPerformed(evt);
            }
        });

        ok_btn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ok_btn.setText("تم");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        progBar_panel.setLayout(new java.awt.CardLayout());

        bar.setOpaque(true);
        progBar_panel.add(bar, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(browser_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(path_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(progBar_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(path_TF)
                    .addComponent(browser_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progBar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browser_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browser_btnActionPerformed
        // TODO add your handling code here:

        backup_FC.setCurrentDirectory(new java.io.File("."));
        backup_FC.setDialogTitle("open");
        backup_FC.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        backup_FC.setAcceptAllFileFilterUsed(false);
        if (backup_FC.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): "
                    + backup_FC.getCurrentDirectory());
            this.path_TF.setText(backup_FC.getSelectedFile().toString());
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_browser_btnActionPerformed
boolean validateForm(){

String path =path_TF.getText();
if(path.isEmpty()){return false;}
return true;


}
    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed

        if(validateForm()){
            ok_btn.setEnabled(false);
            bar.setIndeterminate(true);
            new Worker().execute();
        
        }
    }//GEN-LAST:event_ok_btnActionPerformed
    private class Worker extends SwingWorker<Boolean, Boolean> {

        protected Boolean doInBackground() {
            String dir = path_TF.getText();
            try {
                data_source.export("TEST", dir, "Database_Backup");
                

            } catch (SQLException ex) {
                Logger.getLogger(Backup_panel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Backup_panel.class.getName()).log(Level.SEVERE, null, ex);
            }

            return Boolean.TRUE;
        }

        protected void done() {
            ok_btn.setEnabled(true);
            bar.setIndeterminate(false);
            JOptionPane.showMessageDialog(owner, "تم الحفظ");
                owner.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser backup_FC;
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton browser_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok_btn;
    private javax.swing.JTextField path_TF;
    private javax.swing.JPanel progBar_panel;
    // End of variables declaration//GEN-END:variables
}
