/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.PlainDocument;
import shop.GUI_attachement_pkg.PersonName_STF;
import shop.Validation_pkg.DoubleInputValidator;
import shop.data_source_pkg.DataSourc;
import shop.data_structures_pkg.Person;

/**
 *
 * @author Compu City
 */
public class ConfirmPurchases_price extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmPurchases_price
     */
    DataSourc data_source;
    Main_Frame myFrame;

    public ConfirmPurchases_price(Main_Frame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        initComponents();
        intiatePage();
    }
void fillPurchasedCustomerTable(){
int seasonID=data_source.getCurrentSeason();
   DefaultTableModel dtm = (DefaultTableModel) customers_table.getModel();
        Vector<Object> data = data_source.getAllPurchasesNames(seasonID);
           Vector<Object> temp =new Vector<>();
        for(int i=0;i<data.size();i++){
          Vector<Object> row=(Vector<Object>)data.get(i);
          
        String []str=row.get(3).toString().split("_");
        row.set(3, str[1]);
        data.set(i, row);
        
        }
        dtm.setDataVector(data, customerTable_ColumnTitle);
        customers_table.setModel(dtm);}



    public void intiatePage() {

   this.notes_TA.setText("");
    this.amount_TF.setText(""); 
    this.amount_TF.setText("");
 fillPurchasedCustomerTable();

    }
   String NormalizeinArabic(String str) {

        char[] arabicChars = {'٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'};
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            if (Character.isDigit(str.charAt(i))) {
                builder.append(arabicChars[(int) (str.charAt(i)) - 48]);
            } else {
                builder.append(str.charAt(i));
            }
        }
//        System.out.println("Number in English : " + str);
//        System.out.println("Number In Arabic : " + builder.toString());
        return builder.toString();
    }
    boolean validateForm() {

        String amount = amount_TF.getText();
        String name ="مشتروات_"+ payName_TF.getText();

        if (amount.isEmpty()) {
            this.wraning_label.setText("يجب إدخال المبلغ");
            return false;
        }

        if (!data_source.vallidateSafeWithdrawal(Double.parseDouble(amount))) {
            return false;
        }
        if (name.isEmpty()) {
            this.wraning_label.setText("يجب إدخال الأسم");
            return false;
        }
        Person p = data_source.customerSelectAll(name);
        if (p == null) {
            this.wraning_label.setText("الاسم غير موجود");
            return false;
        }
        this.wraning_label.setText("");
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        results_panel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        detail_table1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        price_RB = new javax.swing.JRadioButton();
        inst_RB = new javax.swing.JRadioButton();
        confirm_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        unConfOrders_Table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        inst_table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        incomeDatainput_panel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        amount_TF = new javax.swing.JTextField();
        paid_label1 = new javax.swing.JLabel();
        report_panel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        notes_TA = new javax.swing.JTextArea();
        intSave_btn = new javax.swing.JButton();
        wraning_label = new javax.swing.JLabel();
        payName_TF = new PersonName_STF(myFrame, "Pcustomer", data_source);
        search_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        search_btn = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        customers_table = new javax.swing.JTable();

        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(900);

        results_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 3, true));
        results_panel.setLayout(new javax.swing.OverlayLayout(results_panel));

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));

        detail_table1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        detail_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الثمن", "عمولة ", "الوهبة", "الفئة", "إجمالي المبلغ", "الناولون", "الصافي", "القائم", "البيان", "تاريخ الفاتورة", "رقم الفاتورة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detail_table1.setRowHeight(25);
        jScrollPane7.setViewportView(detail_table1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel7);

        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        jSplitPane3.setDividerLocation(300);

        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));

        buttonGroup1.add(price_RB);
        price_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        price_RB.setSelected(true);
        price_RB.setText("ثمن الموز");
        price_RB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        price_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        price_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_RBActionPerformed(evt);
            }
        });

        buttonGroup1.add(inst_RB);
        inst_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        inst_RB.setText("مسحوبات الموز");
        inst_RB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inst_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        inst_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inst_RBActionPerformed(evt);
            }
        });

        confirm_btn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        confirm_btn.setText("تأكيد السعر");
        confirm_btn.setEnabled(false);
        confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(inst_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price_RB)
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_RB)
                    .addComponent(inst_RB)
                    .addComponent(confirm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        unConfOrders_Table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unConfOrders_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "الثمن", "الفئة", "الناولون", "القائم", "تاريخ الفاتورة", "رقم الفاتورة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        unConfOrders_Table.setRowHeight(25);
        jScrollPane5.setViewportView(unConfOrders_Table);

        jPanel1.add(jScrollPane5, "unConfOrders_card");

        inst_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ملاحظات", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inst_table.setRowHeight(25);
        jScrollPane1.setViewportView(inst_table);

        jPanel1.add(jScrollPane1, "inst_card");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel4);

        jSplitPane3.setRightComponent(jPanel8);

        jPanel9.setLayout(new javax.swing.OverlayLayout(jPanel9));

        incomeDatainput_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true), "بيانات الداخل", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("الأسم:");

        amount_TF.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        amount_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amount_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_TFActionPerformed(evt);
            }
        });

        paid_label1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        paid_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paid_label1.setText("المبلغ:");

        report_panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ملاحظات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        report_panel2.setLayout(new javax.swing.OverlayLayout(report_panel2));

        jScrollPane9.setWheelScrollingEnabled(false);

        notes_TA.setColumns(20);
        notes_TA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        notes_TA.setLineWrap(true);
        notes_TA.setRows(5);
        notes_TA.setToolTipText("ملاحظات");
        notes_TA.setWrapStyleWord(true);
        notes_TA.setBorder(null);
        jScrollPane9.setViewportView(notes_TA);

        report_panel2.add(jScrollPane9);

        intSave_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        intSave_btn.setText("حفظ");
        intSave_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intSave_btnActionPerformed(evt);
            }
        });

        wraning_label.setBackground(new java.awt.Color(204, 204, 255));
        wraning_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        wraning_label.setForeground(new java.awt.Color(255, 0, 51));
        wraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        payName_TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        payName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout incomeDatainput_panel1Layout = new javax.swing.GroupLayout(incomeDatainput_panel1);
        incomeDatainput_panel1.setLayout(incomeDatainput_panel1Layout);
        incomeDatainput_panel1Layout.setHorizontalGroup(
            incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report_panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panel1Layout.createSequentialGroup()
                        .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount_TF)
                            .addComponent(payName_TF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paid_label1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panel1Layout.createSequentialGroup()
                        .addComponent(wraning_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intSave_btn)))
                .addContainerGap())
        );
        incomeDatainput_panel1Layout.setVerticalGroup(
            incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paid_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(report_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intSave_btn)
                    .addComponent(wraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PlainDocument amount_TF_doc = (PlainDocument)amount_TF.getDocument();
        amount_TF_doc.setDocumentFilter(new DoubleInputValidator(this.amount_TF , this.wraning_label));

        jPanel9.add(incomeDatainput_panel1);

        jSplitPane3.setLeftComponent(jPanel9);

        jPanel6.add(jSplitPane3);

        jSplitPane2.setLeftComponent(jPanel6);

        results_panel.add(jSplitPane2);

        jSplitPane1.setLeftComponent(results_panel);

        search_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(42, 139, 9), 3, true));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        search_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search_btn.setText("تحديث البيانات");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel3.add(search_btn);

        customers_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        customers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "المستحق", "المدفوع", "ثمن الموز", "اسم العميل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customers_table.setRowHeight(25);
        customers_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customers_tableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(customers_table);

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addContainerGap())
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(search_panel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents
 void search(String name) {

        DefaultTableModel dtm = null;
//fill detail table
        dtm = (DefaultTableModel) detail_table1.getModel();
        int seasonID=data_source.getCurrentSeason();
        Vector<Object> data = data_source.getPurchasedOrders(name,myFrame.firdage_id,seasonID);
        dtm.setDataVector(data, PdetailTable_columnTitles);
        detail_table1.setModel(dtm);
setDetail_table1Size();


//fill orders table 
        data = data_source.getPurchasesorders(name,seasonID);
        dtm = (DefaultTableModel) unConfOrders_Table.getModel();
        dtm.setDataVector(data, purchases_columnTitles);
        unConfOrders_Table.setModel(dtm);
        setCustomerOrders_tableSize();
        this.confirm_btn.setEnabled(data.size()>0);
        
        //fill inst table 
        data = data_source.getPurchasedCustomerInsts(name,seasonID);
        dtm = (DefaultTableModel) inst_table.getModel();
        dtm.setDataVector(data, inst_columnTitles);
        inst_table.setModel(dtm);

    }

    void setCustomerOrders_tableSize() {
        //customerOrders_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < unConfOrders_Table.getColumnModel().getColumnCount(); i++) {
            column = unConfOrders_Table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(100);
                    break;
                case 1:
                    column.setPreferredWidth(80);
                    break;
                case 2:
                    column.setPreferredWidth(80);
                    break;
                    case 3:
                    column.setPreferredWidth(100);
                    break;
                case 4:
                    column.setPreferredWidth(200);
                    break;
                case 5:
                    column.setPreferredWidth(40);
                    break;

            }
        }

    }

    void setDetail_table1Size() {
        //customerOrders_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < detail_table1.getColumnModel().getColumnCount(); i++) {
            column = detail_table1.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(100);
                    break;
                case 1:
                    column.setPreferredWidth(80);
                    break;
                case 2:
                    column.setPreferredWidth(80);
                    break;
                     case 3:
                    column.setPreferredWidth(80);
                    break;
                case 4:
                    column.setPreferredWidth(100);
                    break;
                case 5:
                    column.setPreferredWidth(80);
                    break;
                case 6:
                    column.setPreferredWidth(100);
                    break;
                case 7:
                    column.setPreferredWidth(100);
                    break;
                case 8:
                    column.setPreferredWidth(150);
                    break;
                case 9:
                    column.setPreferredWidth(220);
                    break;
                     case 10:
                    column.setPreferredWidth(50);
                    break;

            }
        }

    }


    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
       fillPurchasedCustomerTable();

    }//GEN-LAST:event_search_btnActionPerformed

    private void customers_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customers_tableMouseClicked
         // TODO add your handling code here:

        String name = "";
        Vector<Object> row = (Vector<Object>) ((DefaultTableModel) customers_table.getModel()).getDataVector().get(customers_table.getSelectedRow());
        name = row.get(3).toString();
        search( "مشتروات_" + name);

    }//GEN-LAST:event_customers_tableMouseClicked

    private void intSave_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intSave_btnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String name = "مشتروات_"+payName_TF.getText();
            double amount = Double.parseDouble(amount_TF.getText());
            String notes = notes_TA.getText();
            data_source.purchasedCustomerInstPay(name, amount, notes,myFrame.firdage_id);
            intiatePage();

        }

    }//GEN-LAST:event_intSave_btnActionPerformed

    private void price_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_RBActionPerformed
        // TODO add your handling code here:
        if (price_RB.isSelected()) {
            CardLayout c = (CardLayout) jPanel1.getLayout();
            c.show(jPanel1, "unConfOrders_card");

        }


    }//GEN-LAST:event_price_RBActionPerformed

    private void inst_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inst_RBActionPerformed
        // TODO add your handling code here:

        if (inst_RB.isSelected()) {
            CardLayout c = (CardLayout) jPanel1.getLayout();
            c.show(jPanel1, "inst_card");

        }


    }//GEN-LAST:event_inst_RBActionPerformed

    private void confirm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btnActionPerformed
         // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) unConfOrders_Table.getModel();
        Vector<Object> data = dtm.getDataVector();
        if(data!=null){
        List<Map> table = new ArrayList<>();
        for (int i = 0; i < data.size(); i++) {

            Vector<Object> temp = (Vector<Object>) data.get(i);
            int orderId = Integer.parseInt(String.valueOf(temp.get(5).toString()));
              String s_amount = temp.get(0).toString();
            String SunitePrices = temp.get(1).toString();
            if (s_amount != null&&!s_amount.isEmpty()
                    &&SunitePrices!=null&&!SunitePrices.isEmpty()) {
                double amount = Double.parseDouble(s_amount);
                 double uniteprice = Double.parseDouble(SunitePrices);
                Map<String, Object> m = new HashMap();
                m.put("PURCHASES_ID", orderId);
                m.put("BUY_PRICE", amount);
                m.put("UNITE_PRICE", uniteprice);
                table.add(m);
            }
        }
         data_source.closePurchasesPeriod(table);

        JOptionPane.showMessageDialog(null, "تم تأكيد اسعار الموز ");
        data = null;
        intiatePage();

        }
    }//GEN-LAST:event_confirm_btnActionPerformed

    private void amount_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_TFActionPerformed
        // TODO add your handling code here:
        this.wraning_label.setText("");
    }//GEN-LAST:event_amount_TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_TF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirm_btn;
    private javax.swing.JTable customers_table;
    private javax.swing.JTable detail_table1;
    private javax.swing.JPanel incomeDatainput_panel1;
    private javax.swing.JRadioButton inst_RB;
    private javax.swing.JTable inst_table;
    private javax.swing.JButton intSave_btn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextArea notes_TA;
    private javax.swing.JLabel paid_label1;
    private javax.swing.JTextField payName_TF;
    private javax.swing.JRadioButton price_RB;
    private javax.swing.JPanel report_panel2;
    private javax.swing.JPanel results_panel;
    private javax.swing.JButton search_btn;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTable unConfOrders_Table;
    private javax.swing.JLabel wraning_label;
    // End of variables declaration//GEN-END:variables

    Vector<String> customerTable_ColumnTitle = new Vector<String>(Arrays.asList( "المستحق", "المدفوع", "ثمن الموز", "اسم العميل"));
    Vector<String> PdetailTable_columnTitles = new Vector<String>(Arrays.asList(
        "الثمن", "عمولة ", "الوهبة", "الفئة", "إجمالي المبلغ", "الناولون", "الصافي", "القائم", "البيان", "تاريخ الفاتورة", "رقم الفاتورة"
    ));

    Vector<String> purchases_columnTitles = new Vector<>(Arrays.asList(        "الثمن", "الفئة", "الناولون", "القائم", "تاريخ الفاتورة", "رقم الفاتورة"
));
    Vector<String> inst_columnTitles = new Vector<>(Arrays.asList("ملاحظات", "المبلغ", "التاريخ"));
}
