/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import shop.Validation_pkg.DoubleInputValidator;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author ahmed
 */
public class Draft_panel extends javax.swing.JPanel {

    /**
     * Creates new form Draft_panel
     */
      DataSourc data_source;
    JFrame myFrame;
    public Draft_panel(JFrame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        input_panel = new javax.swing.JPanel();
        unit_label1 = new javax.swing.JLabel();
        amount_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes_TA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        wranning_label = new javax.swing.JLabel();
        date_DP = new org.jdesktop.swingx.JXDatePicker();
        unit_label2 = new javax.swing.JLabel();
        draft_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        draft_table = new javax.swing.JTable();

        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(200);

        input_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 146, 23), 2, true), "إدخال البيانات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        unit_label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label1.setText("المبلغ");

        amount_TF.setFont(new java.awt.Font("B Fantezy", 0, 20)); // NOI18N
        amount_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true), "البيان", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        notes_TA.setColumns(20);
        notes_TA.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        notes_TA.setRows(5);
        jScrollPane1.setViewportView(notes_TA);

        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wranning_label.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        wranning_label.setForeground(new java.awt.Color(255, 0, 0));
        wranning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        unit_label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label2.setText("التاريخ");

        javax.swing.GroupLayout input_panelLayout = new javax.swing.GroupLayout(input_panel);
        input_panel.setLayout(input_panelLayout);
        input_panelLayout.setHorizontalGroup(
            input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_panelLayout.createSequentialGroup()
                .addGroup(input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_DP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amount_TF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit_label1)
                            .addComponent(unit_label2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(wranning_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(input_panelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        input_panelLayout.setVerticalGroup(
            input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_DP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wranning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        PlainDocument amount_TF_doc = (PlainDocument)amount_TF .getDocument();
        amount_TF_doc.setDocumentFilter(new DoubleInputValidator(this.amount_TF , wranning_label));

        jSplitPane1.setRightComponent(input_panel);

        draft_panel.setLayout(new javax.swing.OverlayLayout(draft_panel));

        draft_table.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        draft_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "البيان", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        draft_table.setRowHeight(25);
        jScrollPane2.setViewportView(draft_table);

        draft_panel.add(jScrollPane2);

        jSplitPane1.setLeftComponent(draft_panel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents
void intiatePage(){

    DefaultTableModel dtm=(DefaultTableModel)draft_table.getModel();
    Vector<Object>data=data_source.selectDraft();
    dtm.setDataVector(data, draft_columntitles);
draft_table.setModel(dtm);


}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        if(validateForm()){
        double amount=Double.parseDouble(amount_TF.getText());
        String notes=notes_TA.getText();
        java.util.Date date=date_DP.getDate();
        
        
        data_source.insertDraft(amount, notes, new java.sql.Date(date.getTime()));
        intiatePage();
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed
boolean validateForm(){

String amount =amount_TF.getText();

if(amount.isEmpty()){

this.wranning_label.setText("يجب إدخال المبلغ");
return false;

}

return true;

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_TF;
    private org.jdesktop.swingx.JXDatePicker date_DP;
    private javax.swing.JPanel draft_panel;
    private javax.swing.JTable draft_table;
    private javax.swing.JPanel input_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea notes_TA;
    private javax.swing.JLabel unit_label1;
    private javax.swing.JLabel unit_label2;
    private javax.swing.JLabel wranning_label;
    // End of variables declaration//GEN-END:variables

  Vector<String> draft_columntitles = new Vector<String>(Arrays.asList(
              "البيان", "المبلغ", "التاريخ"
    ));


}
