/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import GUI_attachement_pkg.TextFeildTracker;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.PlainDocument;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import shop.GUI_attachement_pkg.PersonName_STF;
import shop.Validation_pkg.DoubleInputValidator;
import shop.data_source_pkg.DataSourc;
import shop.recources_pkg.ResourceLoader;

/**
 *
 * @author Comu City
 */
public class EditingOrders_panel1 extends javax.swing.JPanel {

    /**
     * Creates new form EditingOrders_panel1
     */
    DataSourc data_source;
    Main_Frame myFrame;
    double netPrice;
    boolean isPurchased;
int seasonID;
    public EditingOrders_panel1(Main_Frame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        isPurchased = false;
        seasonID=data_source.getCurrentSeason();
        initComponents();
        tips_TF.getDocument().addDocumentListener(new TipsValueTracker());
        comminsion_TF.getDocument().addDocumentListener(new CommssionValueTracker());
        intiatePage();
    }

    public class TipsValueTracker implements DocumentListener {

        public TipsValueTracker() {

        }

        void track() {
          
              double tips = (tips_TF.getText().isEmpty())?0:Double.parseDouble(tips_TF.getText());
       
                if (!isPurchased) {
                       tips=(tips_TF.getText().isEmpty())?0:Double.parseDouble(tips_TF.getText());
                        double commsion=(comminsion_TF.getText().isEmpty())?0:Double.parseDouble(comminsion_TF.getText());
                        double total=(totalPice_TF.getText().isEmpty())?0:Double.parseDouble(totalPice_TF.getText());
                        double noloun=(noloun_TF.getText().isEmpty())?0:Double.parseDouble(noloun_TF.getText());
                    double x =  total-(noloun+commsion+tips);
                    netPrice_TF.setText(String.valueOf(x));

                } else if ( isPurchased) {

                    double x = netPrice - tips;
                    comminsion_TF.setText(String.valueOf(x));

                }

        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            track();

        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            track();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            track();
        }

    }

    public class CommssionValueTracker implements DocumentListener {

        public CommssionValueTracker() {

        }

        void track() {
          
              double tips = (tips_TF.getText().isEmpty())?0:Double.parseDouble(tips_TF.getText());
       
                if (!isPurchased) {
                       tips=(tips_TF.getText().isEmpty())?0:Double.parseDouble(tips_TF.getText());
                          double commsion=(comminsion_TF.getText().isEmpty())?0:Double.parseDouble(comminsion_TF.getText());
                        double total=(totalPice_TF.getText().isEmpty())?0:Double.parseDouble(totalPice_TF.getText());
                        double noloun=(noloun_TF.getText().isEmpty())?0:Double.parseDouble(noloun_TF.getText());;
                    double x =  total-(noloun+commsion+tips);
                    netPrice_TF.setText(String.valueOf(x));

                } 

        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            track();

        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            track();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            track();
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wraning_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customers_table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        customerRefresh_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        suggestedOrders_table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        orderID_TF = new javax.swing.JTextField();
        orderDate_TF = new javax.swing.JTextField();
        product_TF = new javax.swing.JTextField();
        noloun_TF = new javax.swing.JTextField();
        grossWeight_TF = new javax.swing.JTextField();
        netWeight_TF = new javax.swing.JTextField();
        ratio_TF = new javax.swing.JTextField();
        unites_TF = new javax.swing.JTextField();
        totalPice_TF = new javax.swing.JTextField();
        comminsion_TF = new javax.swing.JTextField();
        netPrice_TF = new javax.swing.JTextField();
        tips_TF = new javax.swing.JTextField();
        vechileType_TF = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        unit_label8 = new javax.swing.JLabel();
        unit_label2 = new javax.swing.JLabel();
        unit_label10 = new javax.swing.JLabel();
        unit_label4 = new javax.swing.JLabel();
        ratio_label = new javax.swing.JLabel();
        unit_label = new javax.swing.JLabel();
        unit_label1 = new javax.swing.JLabel();
        unit_label9 = new javax.swing.JLabel();
        unit_label5 = new javax.swing.JLabel();
        unit_label7 = new javax.swing.JLabel();
        unit_label6 = new javax.swing.JLabel();
        unit_label3 = new javax.swing.JLabel();
        unit_label11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        orderDet_table = new javax.swing.JTable();
        report_panel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        notes_TA = new javax.swing.JTextArea();
        edit_btn = new javax.swing.JButton();

        wraning_label.setBackground(new java.awt.Color(204, 204, 255));
        wraning_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wraning_label.setForeground(new java.awt.Color(255, 0, 51));
        wraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(700);

        jSplitPane2.setDividerLocation(400);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 122, 15), 2, true), "العملاء", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        customers_table.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "اسم العميل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customers_table.setRowHeight(25);
        customers_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customers_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customers_table);

        customerRefresh_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerRefresh_btn.setText("تحديث");
        customerRefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRefresh_btnActionPerformed(evt);
            }
        });
        jPanel9.add(customerRefresh_btn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 189, 26), 2, true), "الفواتير"));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("الفواتير المقترحة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        suggestedOrders_table.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        suggestedOrders_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الوزن القائم", "اسم الفاتورة", "رقم الفاتورة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suggestedOrders_table.setRowHeight(25);
        suggestedOrders_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestedOrders_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(suggestedOrders_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        jSplitPane1.setRightComponent(jSplitPane2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(7, 199, 235), 3, true), "بيانات الفاتورة"));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true));

        orderID_TF.setEditable(false);
        orderID_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        orderID_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        orderDate_TF.setEditable(false);
        orderDate_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        orderDate_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        product_TF.setEditable(false);
        product_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        product_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        noloun_TF.setEditable(false);
        noloun_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        noloun_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        grossWeight_TF.setEditable(false);
        grossWeight_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        grossWeight_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        netWeight_TF.setEditable(false);
        netWeight_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        netWeight_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ratio_TF.setEditable(false);
        ratio_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        ratio_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        unites_TF.setEditable(false);
        unites_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        unites_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        totalPice_TF.setEditable(false);
        totalPice_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        totalPice_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        comminsion_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        comminsion_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        netPrice_TF.setEditable(false);
        netPrice_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        netPrice_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tips_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        tips_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        vechileType_TF.setEditable(false);
        vechileType_TF.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        vechileType_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratio_TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(orderID_TF)
                    .addComponent(orderDate_TF)
                    .addComponent(product_TF)
                    .addComponent(noloun_TF)
                    .addComponent(grossWeight_TF)
                    .addComponent(netWeight_TF)
                    .addComponent(unites_TF)
                    .addComponent(totalPice_TF)
                    .addComponent(tips_TF)
                    .addComponent(comminsion_TF)
                    .addComponent(netPrice_TF)
                    .addComponent(vechileType_TF))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDate_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noloun_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grossWeight_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netWeight_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratio_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unites_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPice_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tips_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comminsion_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netPrice_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vechileType_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PlainDocument tips_TF_doc = (PlainDocument)tips_TF.getDocument();
        tips_TF_doc.setDocumentFilter(new DoubleInputValidator(this.tips_TF , this.wraning_label));

        unit_label8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label8.setText("إجمالي المبلغ:");

        unit_label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label2.setText("المنتج:");

        unit_label10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label10.setText("عدد السبايط:");

        unit_label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label4.setText("الوزن الصافي:");

        ratio_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ratio_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ratio_label.setText("الفارغ:");

        unit_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label.setText("الوزن القائم:");

        unit_label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label1.setText("رقم الفاتورة:");

        unit_label9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label9.setText("صافي المبلغ:");

        unit_label5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label5.setText("تاريخ الفاتورة:");

        unit_label7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label7.setText("وهبة:");

        unit_label6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label6.setText("العمولة:");

        unit_label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label3.setText("ناولون:");

        unit_label11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label11.setText("البيان");
        unit_label11.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unit_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(unit_label10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ratio_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unit_label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(unit_label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unit_label9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(unit_label11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(unit_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(unit_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ratio_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unit_label7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unit_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_label11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true), "تفاصيل صافي الوزن"));

        orderDet_table.setFont(new java.awt.Font("B Fantezy", 0, 18)); // NOI18N
        orderDet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الوزن", "الفئة", "المبلغ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDet_table.setRowHeight(25);
        jScrollPane4.setViewportView(orderDet_table);

        report_panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ملاحظات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jScrollPane6.setWheelScrollingEnabled(false);

        notes_TA.setColumns(20);
        notes_TA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        notes_TA.setLineWrap(true);
        notes_TA.setRows(5);
        notes_TA.setToolTipText("ملاحظات");
        notes_TA.setWrapStyleWord(true);
        notes_TA.setBorder(null);
        jScrollPane6.setViewportView(notes_TA);

        javax.swing.GroupLayout report_panel2Layout = new javax.swing.GroupLayout(report_panel2);
        report_panel2.setLayout(report_panel2Layout);
        report_panel2Layout.setHorizontalGroup(
            report_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        report_panel2Layout.setVerticalGroup(
            report_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        edit_btn.setText("تحرير");
        edit_btn.setEnabled(false);
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(report_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(report_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel5);

        jScrollPane3.setViewportView(jSplitPane1);

        add(jScrollPane3);
    }// </editor-fold>//GEN-END:initComponents
   boolean validateForm() {
        if (tips_TF.getText().isEmpty()) {

            wraning_label.setText("يجب إدخال الوهبة");
            return false;
        } else {

            wraning_label.setText("");
            return true;
        }
    }
    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            double netWeight = Double.parseDouble(netWeight_TF.getText());
            double totalPrice = Double.parseDouble(totalPice_TF.getText());
            double netPrice = Double.parseDouble(netPrice_TF.getText());
            double tips = Double.parseDouble(tips_TF.getText());
            double commision = Double.parseDouble(comminsion_TF.getText());
            int order_id = Integer.parseInt(orderID_TF.getText());
            double ratio = Double.parseDouble(ratio_TF.getText());
            String notes = notes_TA.getText();

            data_source.editeCustomerOrder(netWeight, totalPrice, netPrice, tips, commision, notes, order_id, ratio);
                        int productid = data_source.getproductIDFormCustomerOrder(order_id);

  
            if (productid == 1) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {

                        try {
                            // TODO add your handling code here:

                            /* Create and display the form */
                            InputStream customerOrder_report
                                    = ResourceLoader.class.getResourceAsStream("reports/CUSTOMER_PRO1_mainReport.jrxml");
                            JasperReport jr = JasperCompileManager.compileReport(customerOrder_report);
                            Map<String, Object> param = new HashMap<String, Object>();

                            param.put("orderID", new Integer(order_id));
                            param.put("SUBREPORT_DIR", ResourceLoader.class.getResource("reports").toString() + "/");
                            param.put("photoHeader", new shop.recources_pkg.ResourceLoader().getReportHeaderImage());
                            param.put(JRParameter.REPORT_LOCALE, new Locale("ar", "AE", "Arabic"));

                            JasperPrint jp = JasperFillManager.fillReport(jr, param, data_source.con);//(jr, param,GATE.data_source.con);
                            //JasperPrintManager.printReport(jp, false);
                            JasperViewer.viewReport(jp, false, new Locale("ar", "AE", "Arabic"));

                        } catch (JRException ex) {
                            Logger.getLogger(BillsDelivery1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                });
            } else if (productid == 2) {

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {

                        try {
                            // TODO add your handling code here:

                            /* Create and display the form */
                            InputStream customerOrder_report
                                    = ResourceLoader.class.getResourceAsStream("reports/customerOrderPro2.jrxml");
                            JasperReport jr = JasperCompileManager.compileReport(customerOrder_report);
                            Map<String, Object> param = new HashMap<String, Object>();

                            param.put("orderID", new Integer(order_id));
                            param.put("SUBREPORT_DIR", ResourceLoader.class.getResource("reports").toString() + "/");
                            param.put("photoHeader", new shop.recources_pkg.ResourceLoader().getReportHeaderImage());
                            param.put(JRParameter.REPORT_LOCALE, new Locale("ar", "AE", "Arabic"));

                            JasperPrint jp = JasperFillManager.fillReport(jr, param, data_source.con);//(jr, param,GATE.data_source.con);
                            //JasperPrintManager.printReport(jp, false);
                            JasperViewer.viewReport(jp, false, new Locale("ar", "AE", "Arabic"));

                        } catch (JRException ex) {
                            Logger.getLogger(BillsDelivery1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                });
            }
            
           intiatePage();
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fillSuggestedOrdersTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void suggestedOrders_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestedOrders_tableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) suggestedOrders_table.getModel();
        Vector<Object> row = (Vector<Object>) dtm.getDataVector().get(suggestedOrders_table.getSelectedRow());
        int order_id = Integer.parseInt(row.get(2).toString());
        String customerName = row.get(1).toString();
        this.tips_TF.setText("");
        if (customerName.startsWith("مشتروات")) {
            isPurchased = true;
            unit_label9.setText("ثمن المشتروات");
        } else {
            isPurchased = false;
            unit_label9.setText("صافي المبلغ");
        }
        Object[][] tableData = null;
        Map<String, String> orderData = new HashMap<>();

        tableData = data_source.getCustomerOrderData(order_id, orderData);
        int product_id = data_source.getproductIDFormCustomerOrder(order_id);
        if (product_id == 2) {
            this.netWeight_TF.setVisible(false);
            this.unit_label4.setVisible(false);
            this.ratio_label.setVisible(false);
            this.unites_TF.setVisible(false);
            this.ratio_TF.setVisible(false);
            this.unit_label10.setVisible(false);
            this.unit_label.setText("العدد");

            Vector<Object> orderDetailData = data_source.getCustomerOrderSellingDetail(order_id, product_id);
            DefaultTableModel dtm2 = (DefaultTableModel) orderDet_table.getModel();
            dtm2.setDataVector(orderDetailData, orderDetProd2_columntitles);
            orderDet_table.setModel(dtm2);

        } else {
            this.netWeight_TF.setVisible(true);
            this.unit_label4.setVisible(true);
            this.ratio_label.setVisible(true);
            this.unites_TF.setVisible(true);
            this.ratio_TF.setVisible(true);
            this.unit_label10.setVisible(true);
            this.unit_label.setText("الوزن القائم");
            Vector<Object> orderDetailData = data_source.getCustomerOrderSellingDetail(order_id, product_id);
            DefaultTableModel dtm2 = (DefaultTableModel) orderDet_table.getModel();
            dtm2.setDataVector(orderDetailData, orderDetPro1_columntitles);
            orderDet_table.setModel(dtm2);

        }
        this.orderID_TF.setText(orderData.get("orderID"));
        this.unites_TF.setText(orderData.get("unites"));
        this.orderDate_TF.setText(orderData.get("orderDate"));
        this.product_TF.setText(orderData.get("product"));
        this.noloun_TF.setText(orderData.get("noloun"));
        this.grossWeight_TF.setText(orderData.get("grossWeight"));
        this.netWeight_TF.setText(orderData.get("netWeight"));

        this.totalPice_TF.setText(orderData.get("totalcost"));
        this.notes_TA.setText(orderData.get("notes"));
        this.vechileType_TF.setText(orderData.get("vechileType"));
        double totalprice = Double.parseDouble(orderData.get("totalcost"));
        double noloun = Double.parseDouble(orderData.get("noloun"));

        double commision = Math.rint(totalprice * .1);
        this.comminsion_TF.setText(String.valueOf(commision));

        double net_Price = totalprice - (noloun + commision);
        netPrice = net_Price;
        this.netPrice_TF.setText(String.valueOf(netPrice));

        double buy_price = Double.parseDouble(orderData.get("BUY_PRICE"));

        if (isPurchased) {
            commision = totalprice - (buy_price + noloun);
            netPrice = commision;
            this.comminsion_TF.setText(String.valueOf(netPrice));
            this.netPrice_TF.setText(String.valueOf(buy_price));

        }

        double totalWeight = Double.parseDouble(orderData.get("grossWeight"));
        double netWeight = Double.parseDouble(orderData.get("netWeight"));
        double ration = totalWeight - netWeight;
        this.ratio_TF.setText(String.valueOf(ration));
        this.edit_btn.setEnabled(true);

    }//GEN-LAST:event_suggestedOrders_tableMouseClicked

    private void customers_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customers_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) customers_table.getModel();
        Vector<Object> row = (Vector<Object>) dtm.getDataVector().get(customers_table.getSelectedRow());
        String customerName = row.get(0).toString();
        if (customerName.startsWith("مشتروات")) {
            isPurchased = true;
            unit_label9.setText("ثمن المشتروات");
        } else {
            isPurchased = false;
            unit_label9.setText("صافي المبلغ");
        }
        search(customerName);
        setCustomerOrders_tableSize();
    }//GEN-LAST:event_customers_tableMouseClicked
    void setCustomerOrders_tableSize() {
        //customerOrders_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < suggestedOrders_table.getColumnModel().getColumnCount(); i++) {
            column = suggestedOrders_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(80);
                    break;
                case 1:
                    column.setPreferredWidth(250);
                    break;
                case 2:
                    column.setPreferredWidth(50);
                    break;

            }
        }

    }
    private void customerRefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRefresh_btnActionPerformed
        // TODO add your handling code here:
        fillCustomersTable();
    }//GEN-LAST:event_customerRefresh_btnActionPerformed
    public void intiatePage() {
        fillCustomersTable();
        fillSuggestedOrdersTable();
        this.edit_btn.setEnabled(false);
        this.orderID_TF.setText("");
        this.orderDate_TF.setText("");
        this.product_TF.setText("");
        this.noloun_TF.setText("");
        this.grossWeight_TF.setText("");
        this.netWeight_TF.setText("");
        this.tips_TF.setText("");
        this.comminsion_TF.setText("");
        this.totalPice_TF.setText("");
        this.netPrice_TF.setText("");
        this.notes_TA.setText("");
        this.unites_TF.setText("");
        this.ratio_TF.setText("");
        

        
        DefaultTableModel dtm = (DefaultTableModel) orderDet_table.getModel();
        dtm.setDataVector(new Object[][]{}, int_columnTitles);
        orderDet_table.setModel(dtm);

    }

    public void fillCustomersTable() {
        //filll customers table
                            int seasonID=data_source.getCurrentSeason();

        DefaultTableModel dtm = (DefaultTableModel) customers_table.getModel();
        Vector<Object> data = data_source.getCustomers(0, 0,seasonID,myFrame.firdage_id);
        dtm.setDataVector(data, customer_columntitles);
        customers_table.setModel(dtm);

    }

    void fillSuggestedOrdersTable() {
                    int seasonID=data_source.getCurrentSeason();

        Vector<Object> data = data_source.getSuggestedOrders(0, 0,seasonID);

        DefaultTableModel dtm = (DefaultTableModel) suggestedOrders_table.getModel();
        dtm.setDataVector(data, suggestedOrders_columnTitles);
        suggestedOrders_table.setModel(dtm);
        setCustomerOrders_tableSize();

    }

    void search(String name) {
 int seasonID=data_source.getCurrentSeason();

        Vector<Object> data = data_source.getCustomerOrders(name, 0, 0,seasonID);
        if (data != null) {
            edit_btn.setEnabled(true);
            DefaultTableModel dtm = (DefaultTableModel) suggestedOrders_table.getModel();
            dtm.setDataVector(data, suggestedOrders_columnTitles);
            suggestedOrders_table.setModel(dtm);
            //  setCustomerOrders_tableSize();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comminsion_TF;
    private javax.swing.JButton customerRefresh_btn;
    private javax.swing.JTable customers_table;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField grossWeight_TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField netPrice_TF;
    private javax.swing.JTextField netWeight_TF;
    private javax.swing.JTextField noloun_TF;
    private javax.swing.JTextArea notes_TA;
    private javax.swing.JTextField orderDate_TF;
    private javax.swing.JTable orderDet_table;
    private javax.swing.JTextField orderID_TF;
    private javax.swing.JTextField product_TF;
    private javax.swing.JTextField ratio_TF;
    private javax.swing.JLabel ratio_label;
    private javax.swing.JPanel report_panel2;
    private javax.swing.JTable suggestedOrders_table;
    private javax.swing.JTextField tips_TF;
    private javax.swing.JTextField totalPice_TF;
    private javax.swing.JLabel unit_label;
    private javax.swing.JLabel unit_label1;
    private javax.swing.JLabel unit_label10;
    private javax.swing.JLabel unit_label11;
    private javax.swing.JLabel unit_label2;
    private javax.swing.JLabel unit_label3;
    private javax.swing.JLabel unit_label4;
    private javax.swing.JLabel unit_label5;
    private javax.swing.JLabel unit_label6;
    private javax.swing.JLabel unit_label7;
    private javax.swing.JLabel unit_label8;
    private javax.swing.JLabel unit_label9;
    private javax.swing.JTextField unites_TF;
    private javax.swing.JTextField vechileType_TF;
    private javax.swing.JLabel wraning_label;
    // End of variables declaration//GEN-END:variables

    Vector<String> customer_columntitles = new Vector<String>(Arrays.asList(
            "اسم العميل"
    ));
    Vector<String> suggestedOrders_columnTitles = new Vector<String>(Arrays.asList(
            "الوزن القائم", "اسم الفاتورة", "رقم الفاتورة"
    ));

    Vector< String> customerOrder_columnTitles = new Vector<String>(Arrays.asList(
            "الوزن القائم", "اسم الفاتورة", "رقم الفاتورة"));

    Vector<String> orderDetPro1_columntitles = new Vector<String>(Arrays.asList(
            "الوزن", "الفئة", "المبلغ"
    ));
    Vector<String> orderDetProd2_columntitles = new Vector<String>(Arrays.asList(
            "العدد", "الفئة", "المبلغ"
    ));
    String[] int_columnTitles = new String[]{};
}
