/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import javax.swing.JFrame;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author ahmed
 */
public class KareemWithdrawals_TappedPanel extends javax.swing.JPanel {

    /**
     * Creates new form KareemWithdrawals
     */
       DataSourc data_source;
    Main_Frame myFrame;
    public KareemWithdrawals_TappedPanel(Main_Frame myFrame,DataSourc data_source) {
         this.data_source=data_source;
        this.myFrame=myFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        labour_panel = new Labours(myFrame, data_source);
        ChemicalSupplier_panel = new ChemicalSupplier(myFrame, data_source);
        variaties_panel = new Vsrieties(myFrame, data_source);
        jPanel1 = new Draft_panel(myFrame, data_source);
        jPanel2 = new SearchContractors(myFrame, data_source);

        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setLayout(new javax.swing.OverlayLayout(this));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labour_panel.setLayout(new javax.swing.OverlayLayout(labour_panel));
        jTabbedPane1.addTab("العمالة", labour_panel);

        ChemicalSupplier_panel.setLayout(new javax.swing.OverlayLayout(ChemicalSupplier_panel));
        jTabbedPane1.addTab("توريدات الكيماوي", ChemicalSupplier_panel);

        variaties_panel.setLayout(new javax.swing.OverlayLayout(variaties_panel));
        jTabbedPane1.addTab("منوعات", variaties_panel);
        jTabbedPane1.addTab("مزكرة", jPanel1);
        jTabbedPane1.addTab("البحث", jPanel2);

        add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("العمال");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChemicalSupplier_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel labour_panel;
    private javax.swing.JPanel variaties_panel;
    // End of variables declaration//GEN-END:variables
}
