/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.PlainDocument;
import shop.GUI_attachement_pkg.PersonAddress_STF;
import shop.GUI_attachement_pkg.PersonName_STF;
import shop.Validation_pkg.DoubleInputValidator;
import shop.Validation_pkg.LongInputValidator;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author ahmed
 */
public class Labours extends javax.swing.JPanel {

    /**
     * Creates new form Labours
     */
    DataSourc data_source;
    Main_Frame myFrame;

    public Labours(Main_Frame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        initComponents();
        inatiatePage();
    }

    boolean validateForm() {

        if (name_TF.getText().isEmpty()) {
            wraning_label.setText("يجب إدخال اسم المقاول");
            return false;

        } else if (amount_TF.getText().isEmpty()) {

            wraning_label.setText("يجب إدخال المبلغ");
            return false;
        } else if (paid_ChB.getState()&&!data_source.vallidateSafeWithdrawal(Double.parseDouble(amount_TF.getText()))) {
            return false;
        } else {
            wraning_label.setText("");
        }
        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        dataInput_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unit_label = new javax.swing.JLabel();
        phone_TF = new javax.swing.JTextField();
        address_TF = new PersonAddress_STF(data_source, myFrame, "customer");
        name_TF = new PersonName_STF(myFrame, "K_L", data_source,address_TF, phone_TF);
        amount_TF = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        wraning_label = new javax.swing.JLabel();
        report_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes_TA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        paid_ChB = new java.awt.Checkbox();
        date_DP = new org.jdesktop.swingx.JXDatePicker();
        unit_label2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        search_btn = new javax.swing.JButton();
        labourName_TF = new PersonName_STF(myFrame, "K_L", data_source,address_TF, phone_TF);
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        all_RB = new javax.swing.JRadioButton();
        shop_RB = new javax.swing.JRadioButton();
        K_RB = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        shopPaid_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        KPaid_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabourAccount_table = new javax.swing.JTable();
        allContractors_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allContractors_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ShopTotal_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ktotal_TF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 452));
        setLayout(new javax.swing.OverlayLayout(this));

        jSplitPane1.setDividerLocation(900);

        dataInput_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "بيانات الخارج"));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("التليفون:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("العنوان:");

        unit_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label.setText("المبلغ:");

        phone_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        phone_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        address_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        address_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        name_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        amount_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amount_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        save_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        save_btn.setText("حفظ");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        wraning_label.setBackground(new java.awt.Color(204, 204, 255));
        wraning_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wraning_label.setForeground(new java.awt.Color(255, 0, 51));
        wraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        report_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "البيان", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jScrollPane2.setWheelScrollingEnabled(false);

        notes_TA.setColumns(20);
        notes_TA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        notes_TA.setLineWrap(true);
        notes_TA.setRows(5);
        notes_TA.setToolTipText("ملاحظات");
        notes_TA.setWrapStyleWord(true);
        notes_TA.setBorder(null);
        jScrollPane2.setViewportView(notes_TA);

        javax.swing.GroupLayout report_panelLayout = new javax.swing.GroupLayout(report_panel);
        report_panel.setLayout(report_panelLayout);
        report_panelLayout.setHorizontalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        report_panelLayout.setVerticalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("اسم المقاول:");

        paid_ChB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        paid_ChB.setLabel("مدفوع");
        paid_ChB.setState(true);

        unit_label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unit_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_label2.setText("التاريخ");

        javax.swing.GroupLayout dataInput_panelLayout = new javax.swing.GroupLayout(dataInput_panel);
        dataInput_panel.setLayout(dataInput_panelLayout);
        dataInput_panelLayout.setHorizontalGroup(
            dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataInput_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataInput_panelLayout.createSequentialGroup()
                        .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(phone_TF)
                            .addComponent(address_TF)
                            .addComponent(amount_TF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unit_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dataInput_panelLayout.createSequentialGroup()
                        .addComponent(paid_ChB, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataInput_panelLayout.createSequentialGroup()
                        .addComponent(date_DP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(unit_label2))
                    .addGroup(dataInput_panelLayout.createSequentialGroup()
                        .addComponent(wraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_btn)))
                .addContainerGap())
        );
        dataInput_panelLayout.setVerticalGroup(
            dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataInput_panelLayout.createSequentialGroup()
                .addComponent(paid_ChB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_DP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(report_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataInput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_btn))
                .addContainerGap())
        );

        PlainDocument customerPhone_TF_doc = (PlainDocument)phone_TF .getDocument();
        customerPhone_TF_doc .setDocumentFilter(new LongInputValidator(this.phone_TF, this.wraning_label));
        PlainDocument amount_TF_doc = (PlainDocument)amount_TF .getDocument();
        amount_TF_doc.setDocumentFilter(new DoubleInputValidator(this.amount_TF , this.wraning_label));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true), "البحث", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        search_btn.setText("بحث");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        labourName_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labourName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        labourName_TF.setMinimumSize(new java.awt.Dimension(6, 30));
        labourName_TF.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("اسم المقاول:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(search_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labourName_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn)
                    .addComponent(labourName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3))
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buttonGroup1.add(all_RB);
        all_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        all_RB.setSelected(true);
        all_RB.setText("الكل");
        all_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        all_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        all_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_RBActionPerformed(evt);
            }
        });
        jPanel6.add(all_RB);

        buttonGroup1.add(shop_RB);
        shop_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shop_RB.setText("المحل");
        shop_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shop_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        shop_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop_RBActionPerformed(evt);
            }
        });
        jPanel6.add(shop_RB);

        buttonGroup1.add(K_RB);
        K_RB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        K_RB.setText("كريم");
        K_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        K_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        K_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_RBActionPerformed(evt);
            }
        });
        jPanel6.add(K_RB);

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));

        shopPaid_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        shopPaid_TF.setForeground(new java.awt.Color(255, 0, 51));
        shopPaid_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shopPaid_TF.setCaretColor(new java.awt.Color(255, 0, 0));
        shopPaid_TF.setEnabled(false);
        shopPaid_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setText("المحل");

        KPaid_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        KPaid_TF.setForeground(new java.awt.Color(255, 0, 0));
        KPaid_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KPaid_TF.setCaretColor(new java.awt.Color(255, 0, 0));
        KPaid_TF.setEnabled(false);
        KPaid_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("كريم");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopPaid_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KPaid_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(KPaid_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(shopPaid_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LabourAccount_table.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LabourAccount_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "البيان", "مدفوع", "المبلغ", "التاريخ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LabourAccount_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabourAccount_table.setGridColor(new java.awt.Color(2, 106, 2));
        LabourAccount_table.setRowHeight(30);
        LabourAccount_table.setRowMargin(2);
        jScrollPane1.setViewportView(LabourAccount_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(dataInput_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataInput_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel3);

        allContractors_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 3, true), "المقاولين"));

        allContractors_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        allContractors_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "الإجمالي", "اسم المقاول"
            }
        ));
        allContractors_table.setRowHeight(25);
        allContractors_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allContractors_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(allContractors_table);

        ShopTotal_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ShopTotal_TF.setForeground(new java.awt.Color(255, 0, 0));
        ShopTotal_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShopTotal_TF.setCaretColor(new java.awt.Color(255, 0, 0));
        ShopTotal_TF.setEnabled(false);
        ShopTotal_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("المحل");

        Ktotal_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ktotal_TF.setForeground(new java.awt.Color(255, 0, 0));
        Ktotal_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ktotal_TF.setCaretColor(new java.awt.Color(255, 0, 0));
        Ktotal_TF.setEnabled(false);
        Ktotal_TF.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("كريم");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Ktotal_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShopTotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ShopTotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(Ktotal_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout allContractors_panelLayout = new javax.swing.GroupLayout(allContractors_panel);
        allContractors_panel.setLayout(allContractors_panelLayout);
        allContractors_panelLayout.setHorizontalGroup(
            allContractors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allContractors_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        allContractors_panelLayout.setVerticalGroup(
            allContractors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allContractors_panelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(allContractors_panel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String name = name_TF.getText();
            String address = address_TF.getText();
            String phone = phone_TF.getText();
            String type = "K_L";
            double amount = Double.parseDouble(amount_TF.getText());
            String report = notes_TA.getText();
            int paid = (paid_ChB.getState()) ? 1 : 0;
            java.util.Date date = date_DP.getDate();
            int season_id = data_source.getCurrentSeason();
            data_source.contractorTransaction(name, address, phone, type, amount, report, myFrame.firdage_id, paid, new java.sql.Date(date.getTime()), season_id);
            inatiatePage();

        }
    }//GEN-LAST:event_save_btnActionPerformed
    void setLabourAccount_tableSize() {
        // LabourAccount_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < LabourAccount_table.getColumnModel().getColumnCount(); i++) {
            column = LabourAccount_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(250);
                    break;
                case 1:
                    column.setPreferredWidth(30);
                    break;
                case 2:
                    column.setPreferredWidth(80);
                    break;
                case 3:
                    column.setPreferredWidth(270);
                    break;

            }
        }

    }

    private void allContractors_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allContractors_tableMouseClicked
        // TODO add your handling code here:
        int index = allContractors_table.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) allContractors_table.getModel();
        Vector<Object> row = (Vector<Object>) dtm.getDataVector().get(index);
        String name = (String) row.get(1);
        searchContAccount(name);
    }//GEN-LAST:event_allContractors_tableMouseClicked

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        searchContAccount(labourName_TF.getText());
    }//GEN-LAST:event_search_btnActionPerformed

    private void K_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_RBActionPerformed
        // TODO add your handling code here:
        if(K_RB.isSelected()){
        int selected=allContractors_table.getSelectedRow();
        if(selected>-1){
          DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
             String   name=dtm.getValueAt(selected, 1).toString();
                    searchContAccount(name);

        }
        
       else if(!name_TF.getText().isEmpty()){
            searchContAccount(name_TF.getText());
        
        
        }
        
        
        
        }
        
    }//GEN-LAST:event_K_RBActionPerformed

    private void shop_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop_RBActionPerformed
        // TODO add your handling code here:
        if(shop_RB.isSelected()){
        int selected=allContractors_table.getSelectedRow();
        if(selected>-1){
                
                
                DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
             String   name=dtm.getValueAt(selected, 1).toString();
                    searchContAccount(name);

        }
        
       else if(!name_TF.getText().isEmpty()){
            searchContAccount(name_TF.getText());
        
        
        }
        
        
        
        }
    }//GEN-LAST:event_shop_RBActionPerformed

    private void all_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_RBActionPerformed
        // TODO add your handling code here:
        if(all_RB.isSelected()){
        int selected=allContractors_table.getSelectedRow();
        if(selected>-1){
          DefaultTableModel dtm=(DefaultTableModel)allContractors_table.getModel();
             String   name=dtm.getValueAt(selected, 1).toString();
                    searchContAccount(name);

        }
        
       else if(!name_TF.getText().isEmpty()){
            searchContAccount(name_TF.getText());
        
        
        }
        
        
        
        }
    }//GEN-LAST:event_all_RBActionPerformed
    void inatiatePage() {
        this.name_TF.setText("");
        this.address_TF.setText("");
        this.phone_TF.setText("");
        this.amount_TF.setText("");
        this.notes_TA.setText("");

        int SeasonID = data_source.getCurrentSeason();
        double ktotal = data_source.getKTypeWithdrawal("K_L", SeasonID, 0);
        double Shoptotal = data_source.getKTypeWithdrawal("K_L", SeasonID, 1);

        this.ShopTotal_TF.setText(String.valueOf(Shoptotal));
        this.Ktotal_TF.setText(String.valueOf(ktotal));

        fillAllContractorsTable();

    }

    void fillAllContractorsTable() {
 int seasonID=data_source.getCurrentSeason();
        Vector<Object> data = data_source.getAllContractors("K_L",seasonID);
        DefaultTableModel dtm = (DefaultTableModel) allContractors_table.getModel();
        dtm.setDataVector(data, allcont_column_titles);

    }

    void searchContAccount(String Name) {
        int seasonID=data_source.getCurrentSeason();
     
         int sort=2;
    if(K_RB.isSelected()){sort=0;}
    else if(shop_RB.isSelected()){sort=1;}
        Object[][] table = data_source.getContractorAccount(Name, "K_L",sort,seasonID);
        DefaultTableModel dtm = (DefaultTableModel) LabourAccount_table.getModel();
        dtm.setDataVector(table, contractor_columnsTitle);
        LabourAccount_table.setModel(dtm);
        setLabourAccount_tableSize();

        double kPaid = data_source.getContractorWithadrawal(Name, 0,seasonID);
        double kshop = data_source.getContractorWithadrawal(Name, 1,seasonID);

        shopPaid_TF.setText(String.valueOf(kshop));
        KPaid_TF.setText(String.valueOf(kPaid));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KPaid_TF;
    private javax.swing.JRadioButton K_RB;
    private javax.swing.JTextField Ktotal_TF;
    private javax.swing.JTable LabourAccount_table;
    private javax.swing.JTextField ShopTotal_TF;
    private javax.swing.JTextField address_TF;
    private javax.swing.JPanel allContractors_panel;
    private javax.swing.JTable allContractors_table;
    private javax.swing.JRadioButton all_RB;
    private javax.swing.JTextField amount_TF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel dataInput_panel;
    private org.jdesktop.swingx.JXDatePicker date_DP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField labourName_TF;
    private javax.swing.JTextField name_TF;
    private javax.swing.JTextArea notes_TA;
    private java.awt.Checkbox paid_ChB;
    private javax.swing.JTextField phone_TF;
    private javax.swing.JPanel report_panel;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField shopPaid_TF;
    private javax.swing.JRadioButton shop_RB;
    private javax.swing.JLabel unit_label;
    private javax.swing.JLabel unit_label2;
    private javax.swing.JLabel wraning_label;
    // End of variables declaration//GEN-END:variables

    String[] contractor_columnsTitle = new String[]{
        "البيان", "مدفوع", "المبلغ", "التاريخ"
    };

    Vector<Object> allcont_column_titles = new Vector<>(Arrays.asList(
            "الإجمالي", "اسم المقاول"
    ));

}
