/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.awt.Color;
import java.util.Arrays;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.PlainDocument;
import shop.GUI_attachement_pkg.PersonName_STF;
import shop.Validation_pkg.DoubleInputValidator;
import shop.data_source_pkg.DataSourc;
import shop.test.MultiSpanCellTable;

/**
 *
 * @author ahmed
 */
public class Loans extends javax.swing.JPanel {

    /**
     * Creates new form Loans
     */
    DataSourc data_source;
    JFrame myFrame;
    Vector<Object> orderHeaderData;

    public Loans(JFrame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        initComponents();
        name_TF.getDocument().addDocumentListener(new NameValueTracker());
        intiatePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        endLaon_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        collected_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        startLaon_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sellerLoans_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Permenant_RB = new javax.swing.JRadioButton();
        temp_RB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        search_btn = new javax.swing.JButton();
        name_TF1 = new PersonName_STF(myFrame, "seller", data_source);
        jLabel5 = new javax.swing.JLabel();
        paying_panel = new javax.swing.JPanel();
        name_TF = new PersonName_STF(myFrame, "seller", data_source);
        jLabel3 = new javax.swing.JLabel();
        paid_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        report_panel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        notes_TA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        wraning_label = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        orderDetail_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderHeader_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inst_table = new javax.swing.JTable();

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 2, true));

        endLaon_TF.setEditable(false);
        endLaon_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        endLaon_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endLaon_TF.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel8.add(endLaon_TF);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ذمامات نهاية العام");
        jPanel8.add(jLabel2);

        collected_TF.setEditable(false);
        collected_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        collected_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        collected_TF.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel8.add(collected_TF);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("التحصيل");
        jPanel8.add(jLabel6);

        startLaon_TF.setEditable(false);
        startLaon_TF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        startLaon_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startLaon_TF.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel8.add(startLaon_TF);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ذمامات بداية العام");
        jPanel8.add(jLabel1);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 165, 46), 3), "البحث عن بياع", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        sellerLoans_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellerLoans_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "إجمالي ثمن الموز", "المبلغ المستحق", "اسم البياع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sellerLoans_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        sellerLoans_table.setRowHeight(25);
        sellerLoans_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellerLoans_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sellerLoans_table);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buttonGroup1.add(Permenant_RB);
        Permenant_RB.setText("دائم");
        Permenant_RB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Permenant_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Permenant_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Permenant_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Permenant_RBActionPerformed(evt);
            }
        });

        buttonGroup1.add(temp_RB);
        temp_RB.setText("مؤقت");
        temp_RB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temp_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        temp_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp_RBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Permenant_RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temp_RB)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Permenant_RB)
                    .addComponent(temp_RB, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        search_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search_btn.setText("بحث");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        name_TF1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_TF1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("اسم البياع:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_TF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        paying_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true), "بيانات الدفع", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        name_TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        name_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("اسم البياع:");

        paid_TF.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        paid_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paid_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_TFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("المبلغ:");

        report_panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ملاحظات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        report_panel2.setLayout(new javax.swing.OverlayLayout(report_panel2));

        jScrollPane6.setWheelScrollingEnabled(false);

        notes_TA.setColumns(20);
        notes_TA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        notes_TA.setLineWrap(true);
        notes_TA.setRows(22);
        notes_TA.setToolTipText("ملاحظات");
        notes_TA.setWrapStyleWord(true);
        notes_TA.setBorder(null);
        jScrollPane6.setViewportView(notes_TA);

        report_panel2.add(jScrollPane6);

        jButton1.setText("إتمام الدفع");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wraning_label.setBackground(new java.awt.Color(204, 204, 255));
        wraning_label.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        wraning_label.setForeground(new java.awt.Color(255, 0, 51));
        wraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paying_panelLayout = new javax.swing.GroupLayout(paying_panel);
        paying_panel.setLayout(paying_panelLayout);
        paying_panelLayout.setHorizontalGroup(
            paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paying_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paying_panelLayout.createSequentialGroup()
                        .addComponent(name_TF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(report_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paying_panelLayout.createSequentialGroup()
                        .addComponent(paid_TF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paying_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(wraning_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        paying_panelLayout.setVerticalGroup(
            paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paying_panelLayout.createSequentialGroup()
                .addGroup(paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paid_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(report_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paying_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(wraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PlainDocument paid_TF_doc = (PlainDocument)paid_TF.getDocument();
        paid_TF_doc.setDocumentFilter(new DoubleInputValidator(this.paid_TF , this.wraning_label));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paying_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paying_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane2.setTopComponent(jPanel2);

        orderDetail_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        orderDetail_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "اسم الفاتورة", "المبلغ", "فئة", "الغدد", "الصافي", "الوزن القائم", "المنتج"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetail_table.setRowHeight(25);
        jScrollPane4.setViewportView(orderDetail_table);

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jSplitPane3.setDividerLocation(600);

        jPanel5.setLayout(new javax.swing.OverlayLayout(jPanel5));

        orderHeader_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        orderHeader_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "إجمالي المبلغ", "رقم الثلاجة", "تاريخ الطلب"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderHeader_table.setRowHeight(25);
        orderHeader_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderHeader_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(orderHeader_table);

        jPanel5.add(jScrollPane3);

        jSplitPane3.setRightComponent(jPanel5);

        jPanel7.setLayout(new javax.swing.OverlayLayout(jPanel7));

        inst_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ملاحظات", "المبلغ", "تاريخ الدفع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inst_table.setRowHeight(25);
        jScrollPane1.setViewportView(inst_table);

        jPanel7.add(jScrollPane1);

        jSplitPane3.setLeftComponent(jPanel7);

        jPanel1.add(jSplitPane3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setBottomComponent(jPanel6);

        jScrollPane7.setViewportView(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> deepCopy(Vector<Object> source) {
        Vector<Object> temp_source;
        Vector<Object> temp_destination;
        Object x;
        Vector<Object> distination = new Vector<>();
        for (int i = 0; i < source.size(); i++) {
            temp_source = (Vector<Object>) source.get(i);
            //distination.add(temp);
            temp_destination = new Vector<>();
            for (int k = 0; k < temp_source.size(); k++) {

                x = temp_source.get(k);
                temp_destination.add(x);

            }
            distination.add(temp_destination);

        }
        return distination;
    }

    String NormalizeinArabic(String str) {

        char[] arabicChars = {'٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'};
        if (str == null) {
            return str;
        }
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            if (Character.isDigit(str.charAt(i))) {
                builder.append(arabicChars[(int) (str.charAt(i)) - 48]);
            } else {
                builder.append(str.charAt(i));
            }
        }
//        System.out.println("Number in English : " + str);
//        System.out.println("Number In Arabic : " + builder.toString());
        return builder.toString();
    }

    void searchForSeller(String name) {
        int seasonID = data_source.getCurrentSeason();
        double sellerLoan = data_source.getSellerLoan(data_source.sellerSelectAll(name).getId(), data_source.getCurrentSeason());
        double totalAmount=data_source.getSellerOrderTotalPrice(name,seasonID);
        if (sellerLoan == -1) {
            JOptionPane.showMessageDialog(null, "لا توجد نتائج ");

        } else {

            DefaultTableModel dtm = (DefaultTableModel) sellerLoans_table.getModel();
            Vector<Object> row = new Vector();
            row.add(new Vector<Object>(Arrays.asList(String.valueOf(totalAmount),(String.valueOf(sellerLoan)), name)));
            dtm.setDataVector(row, VsellersLoans_columnTitles);

            sellerLoans_table.setModel(dtm);

            Vector<Object> data = data_source.getSellerOrders(name, 0, 0, seasonID);
            orderHeaderData = deepCopy(data);

            dtm = (DefaultTableModel) orderHeader_table.getModel();
            dtm.setDataVector(data, orderHeader_columnTitles);
            orderHeader_table.setModel(dtm);
                //getSellerInstallement

            Vector<Object> data2 = data_source.getSellerInstallement(name, 0, seasonID);

            DefaultTableModel dtm2 = (DefaultTableModel) inst_table.getModel();
            dtm2.setDataVector(data2, inst_columnTitles);
            inst_table.setModel(dtm2);

        }
        
         refrishLoan();

    }
    private void temp_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp_RBActionPerformed
        // TODO add your handling code here:
        //TEMPERORY
        if (temp_RB.isSelected()) {
            int seasonID = data_source.getCurrentSeason();

            Object[][] data = data_source.getActiveSellersLoans("TEMPERORY",seasonID);
            DefaultTableModel dtm = (DefaultTableModel) sellerLoans_table.getModel();
            dtm.setDataVector(data, sellersLoans_columnTitles);
            sellerLoans_table.setModel(dtm);
             refrishLoan();
            
        }
    }//GEN-LAST:event_temp_RBActionPerformed

    private void Permenant_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Permenant_RBActionPerformed
        // TODO add your handling code here:
        //PERMENANT
        if (Permenant_RB.isSelected()) {
                        int seasonID = data_source.getCurrentSeason();

            Object[][] data = data_source.getActiveSellersLoans("PERMENANT",seasonID);
            DefaultTableModel dtm = (DefaultTableModel) sellerLoans_table.getModel();
            dtm.setDataVector(data, sellersLoans_columnTitles);
            sellerLoans_table.setModel(dtm);
            
             refrishLoan();
        }
    }//GEN-LAST:event_Permenant_RBActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String sellerName = name_TF1.getText();
        searchForSeller(sellerName);
    }//GEN-LAST:event_search_btnActionPerformed

    private void sellerLoans_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellerLoans_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) sellerLoans_table.getModel();
        Vector<Object> row = (Vector<Object>) dtm.getDataVector().get(sellerLoans_table.getSelectedRow());
        String sellerName = (row.get(2).toString());
        searchForSeller(sellerName);


    }//GEN-LAST:event_sellerLoans_tableMouseClicked

    public class NameValueTracker implements DocumentListener {

        public NameValueTracker() {

        }

        void track() {
            wraning_label.setText("");

        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            track();

        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            track();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            track();
        }

    }

    void intiatePage() {
        this.Permenant_RB.setSelected(true);
        Object[][] data = new Object[][]{{}};
        DefaultTableModel dtm = (DefaultTableModel) orderHeader_table.getModel();

        dtm.setDataVector(new Vector<Object>(), orderHeader_columnTitles);
        orderHeader_table.setModel(dtm);

        dtm = (DefaultTableModel) inst_table.getModel();
        dtm.setDataVector(new Vector<Object>(), inst_columnTitles);
        inst_table.setModel(dtm);

        dtm = (DefaultTableModel) orderDetail_table.getModel();
        dtm.setDataVector(new Vector<Object>(), orderDetail_columnTitles);
        orderDetail_table.setModel(dtm);
        
        this.name_TF.setText("");
       refrishLoan();

    }
void refrishLoan(){
//collected_TF  
        int seasonID=data_source.getCurrentSeason();
        double seasonStartSellersLoan = data_source.getSeasonStartTotalSellersLoan(seasonID);
        double seasonEndSellersLoan = data_source.getSeasonEndTotalSellersLoan(seasonID);
        this.startLaon_TF.setText(NormalizeinArabic(String.valueOf(seasonStartSellersLoan)));
        this.endLaon_TF.setText(NormalizeinArabic(String.valueOf(seasonEndSellersLoan)));
        this.collected_TF.setText(NormalizeinArabic(String.valueOf(seasonEndSellersLoan-seasonStartSellersLoan)));

}
    boolean vaalidatePaying() {
        String customerName = name_TF.getText();

        if (data_source.sellerSelectAll(customerName) == null) {
            this.wraning_label.setText("البياع غير مسجل");
            return false;

        }

        double sellerLoan = data_source.getSellerLoan(data_source.sellerSelectAll(customerName).getId(), data_source.getCurrentSeason());
        double amount = Double.parseDouble(paid_TF.getText());

        if (sellerLoan < amount) {
            this.wraning_label.setText("المبلغ اكبر من المستحق   :" + sellerLoan);
            return false;

        }

        return true;

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String customerName = name_TF.getText();
        if (vaalidatePaying()) {
            double amount = Double.parseDouble(paid_TF.getText());
            String report = notes_TA.getText();
            data_source.instalementTransaction(customerName, amount, report);
            wraning_label.setForeground(Color.BLUE);

            this.wraning_label.setText("تم الدفع");
            intiatePage();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void orderHeader_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderHeader_tableMouseClicked
        // TODO add your handling code here:
        int index = orderHeader_table.getSelectedRow();
        Object fridageNumber = ((Vector<Object>) (((DefaultTableModel) (orderHeader_table.getModel())).getDataVector().get(index))).get(1);
        if (!fridageNumber.toString().isEmpty()) {
            Vector<Object> row = (Vector<Object>) orderHeaderData.get(index);

            int id = Integer.parseInt(row.get(3).toString());

            Vector<Object> data = data_source.getSellerOrderDetail(id);
            if (data != null) {

                DefaultTableModel dtm = (DefaultTableModel) orderDetail_table.getModel();
                dtm.setDataVector(data, orderDetail_columnTitles);
                orderDetail_table.setModel(dtm);
                setOrderDetail_tableSize();
            }
        }
    }//GEN-LAST:event_orderHeader_tableMouseClicked

    private void name_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TFActionPerformed
        // TODO add your handling code here:
        this.wraning_label.setText("");
    }//GEN-LAST:event_name_TFActionPerformed

    private void paid_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_TFActionPerformed
        // TODO add your handling code here:
        this.wraning_label.setText("");
    }//GEN-LAST:event_paid_TFActionPerformed
    void setorderHeader_tableSize() {
//detail_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < inst_table.getColumnModel().getColumnCount(); i++) {
            column = inst_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(120);
                    break;
                case 1:
                    column.setPreferredWidth(250);
                    break;

            }
        }

    }

    void setInst_tableSize() {
//detail_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < inst_table.getColumnModel().getColumnCount(); i++) {
            column = inst_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(150);
                    break;
                case 1:
                    column.setPreferredWidth(100);
                    break;
                case 2:
                    column.setPreferredWidth(180);
                    break;

            }
        }

    }

    void setOrderDetail_tableSize() {
//detail_table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn column = null;
        for (int i = 0; i < orderDetail_table.getColumnModel().getColumnCount(); i++) {
            column = orderDetail_table.getColumnModel().getColumn(i);

            switch (i) {
                case 0:
                    column.setPreferredWidth(200);
                    break;
                case 1:
                    column.setPreferredWidth(100);
                    break;
                case 2:
                    column.setPreferredWidth(80);
                    break;
                case 3:
                    column.setPreferredWidth(80);
                    break;
                case 4:
                    column.setPreferredWidth(100);
                    break;
                case 5:
                    column.setPreferredWidth(100);
                    break;
                case 6:
                    column.setPreferredWidth(150);
                    break;
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Permenant_RB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField collected_TF;
    private javax.swing.JTextField endLaon_TF;
    private javax.swing.JTable inst_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextField name_TF;
    private javax.swing.JTextField name_TF1;
    private javax.swing.JTextArea notes_TA;
    private javax.swing.JTable orderDetail_table;
    private javax.swing.JTable orderHeader_table;
    private javax.swing.JTextField paid_TF;
    private javax.swing.JPanel paying_panel;
    private javax.swing.JPanel report_panel2;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton search_btn;
    private javax.swing.JTable sellerLoans_table;
    private javax.swing.JTextField startLaon_TF;
    private javax.swing.JRadioButton temp_RB;
    private javax.swing.JLabel wraning_label;
    // End of variables declaration//GEN-END:variables

    String[] sellersLoans_columnTitles = new String[]{
      "إجمالي ثمن الموز",  "المبلغ المستحق", "اسم البياع"
    };
    Vector<String> VsellersLoans_columnTitles = new Vector(Arrays.asList("إجمالي ثمن الموز","المبلغ المستحق", "اسم البياع"));

 Vector<Object> orderDetail_columnTitles = new Vector<Object>(Arrays.asList(        "اسم العميل", "المبلغ", "فئة", "الغدد", "الصافي", "الوزن القائم", "المنتج"
));
    
    Vector<String> orderHeader_columnTitles = new Vector<String>(Arrays.asList("إجمالي المبلغ", "رقم الثلاجة", "تاريخ الطلب"));

    Vector<String> inst_columnTitles = new Vector<String>(Arrays.asList("ملاحظات", "المبلغ", "تاريخ الدفع"));

}
