/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;
import shop.recources_pkg.ResourceLoader;
import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import javax.swing.JScrollPane;
import shop.GUI_attachement_pkg.Image_panel;
import shop.StartWindow;
import shop.data_source_pkg.DataSourc;
/**
 *
 * @author ahmed
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    DataSourc data_source;
    ResourceLoader RL;
    inputOutputTappedPanel inputOutputtab;
    
    boolean archivedLoaded;
public int firdage_id;




 Inventor inventorPage;
 Sellers_panel sellersPage;
 Customers_Panel customersPanel;
    public Main_Frame( DataSourc data_source,int firdage_id) {
        this.data_source=data_source;
        RL=new ResourceLoader();
        archivedLoaded=false;
        
      
        
        
       // StartWindow.monitor_label.setText("بناء المكونات");
       StartWindow.connecting_PB.setValue(60);
       this.firdage_id=firdage_id;
    
        initComponents();
       inputOutputtab=   new inputOutputTappedPanel(this, data_source);
       StartWindow.connecting_PB.setValue(65);
    

       
        String fridageName = (firdage_id == 1) ? "محل رقم 18" : "محل رقم 21";
        this.fridage_label.setText(NormalizeinArabic(fridageName));       
       
       
      card_panel.add(new Image_panel(RL.getwelcome_image()),"welcome_card");
      
       customersPanel=new Customers_Panel(this,data_source);
       card_panel.add(customersPanel,"customers_card");
       StartWindow.connecting_PB.setValue(75);
       
       sellersPage= new Sellers_panel(this,data_source);
       card_panel.add(sellersPage,"sellers_card");
       StartWindow.connecting_PB.setValue(90);
       
       card_panel.add(inputOutputtab,"expense_card");
       StartWindow.connecting_PB.setValue(95);
       card_panel.add(new JScrollPane(new KareemWithdrawals_TappedPanel(this,data_source)),"KareemWithdrawals_card");
       card_panel.add(new Orders(this, data_source),"Orders_card");
       
       inventorPage  =new Inventor(this, data_source);
       card_panel.add(inventorPage,"inventory_card");
       
       StartWindow.connecting_PB.setValue(100);
//       StartWindow.monitor_label.setText("تم الأتصال");

       jDialog2.add(new loginSetting_panel(jDialog2,data_source));
      dialgContainer_panel.add(new Recovery_panel(),"recovery");
      dialgContainer_panel.add(new Settelement_panel(jDialog1,data_source),"settelement");
      dialgContainer_panel.add(new Backup_panel(jDialog1,data_source),"backUP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDialog1 = new javax.swing.JDialog();
        dialgContainer_panel = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog2 = new javax.swing.JDialog();
        archive_frame = new javax.swing.JFrame("الأرشيف");
        jPanel1 = new javax.swing.JPanel();
        photo_panel = new javax.swing.JPanel();
        customersCardImage_panel = new Image_panel(RL.getCustomersBook());
        expenes_panel = new Image_panel(RL.getExpenesBookImage());
        kareemWithadralsCardImage_panel = new Image_panel(RL.getKareemWithDrawals_image());
        OrderCardImage_panel = new Image_panel(RL.getorders_image());
        inventory_panel = new Image_panel(RL.getInventoryImage());
        settings_panel = new Image_panel(RL.getSettingsImage());
        sellersCardImage_panel = new Image_panel(RL.getSellersBookImage());
        jScrollPane2 = new javax.swing.JScrollPane();
        sections_panel = new javax.swing.JPanel();
        customers_btn = new javax.swing.JButton();
        sellers_btn = new javax.swing.JButton();
        expenes_btn = new javax.swing.JButton();
        kareemWthdrawals_btn = new javax.swing.JButton();
        kareemWthdrawals_btn1 = new javax.swing.JButton();
        inventory_btn = new javax.swing.JButton();
        fridage_label = new javax.swing.JLabel();
        card_panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        backUp_MI = new javax.swing.JMenuItem();
        dailyWork_MI = new javax.swing.JMenuItem();
        changePassword_MI = new javax.swing.JMenuItem();
        recovery_MI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        archive_MI = new javax.swing.JMenuItem();

        log_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout log_panelLayout = new javax.swing.GroupLayout(log_panel);
        log_panel.setLayout(log_panelLayout);
        log_panelLayout.setHorizontalGroup(
            log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, log_panelLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        log_panelLayout.setVerticalGroup(
            log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, log_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(400, 200));
        jDialog1.getContentPane().setLayout(new javax.swing.OverlayLayout(jDialog1.getContentPane()));

        dialgContainer_panel.setLayout(new java.awt.CardLayout());
        jDialog1.getContentPane().add(dialgContainer_panel);

        jDialog2.setResizable(false);
        jDialog2.setSize(new java.awt.Dimension(400, 290));
        jDialog2.getContentPane().setLayout(new javax.swing.OverlayLayout(jDialog2.getContentPane()));

        archive_frame.setSize(new java.awt.Dimension(900, 800));
        archive_frame.getContentPane().setLayout(new javax.swing.OverlayLayout(archive_frame.getContentPane()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        photo_panel.setPreferredSize(new java.awt.Dimension(700, 200));
        photo_panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout customersCardImage_panelLayout = new javax.swing.GroupLayout(customersCardImage_panel);
        customersCardImage_panel.setLayout(customersCardImage_panelLayout);
        customersCardImage_panelLayout.setHorizontalGroup(
            customersCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        customersCardImage_panelLayout.setVerticalGroup(
            customersCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(customersCardImage_panel, "customers_Imagecard");

        javax.swing.GroupLayout expenes_panelLayout = new javax.swing.GroupLayout(expenes_panel);
        expenes_panel.setLayout(expenes_panelLayout);
        expenes_panelLayout.setHorizontalGroup(
            expenes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        expenes_panelLayout.setVerticalGroup(
            expenes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(expenes_panel, "expense_imageCard");

        javax.swing.GroupLayout kareemWithadralsCardImage_panelLayout = new javax.swing.GroupLayout(kareemWithadralsCardImage_panel);
        kareemWithadralsCardImage_panel.setLayout(kareemWithadralsCardImage_panelLayout);
        kareemWithadralsCardImage_panelLayout.setHorizontalGroup(
            kareemWithadralsCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        kareemWithadralsCardImage_panelLayout.setVerticalGroup(
            kareemWithadralsCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(kareemWithadralsCardImage_panel, "kareemWith_imageCard");

        javax.swing.GroupLayout OrderCardImage_panelLayout = new javax.swing.GroupLayout(OrderCardImage_panel);
        OrderCardImage_panel.setLayout(OrderCardImage_panelLayout);
        OrderCardImage_panelLayout.setHorizontalGroup(
            OrderCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        OrderCardImage_panelLayout.setVerticalGroup(
            OrderCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(OrderCardImage_panel, "orders_ImageCard");

        javax.swing.GroupLayout inventory_panelLayout = new javax.swing.GroupLayout(inventory_panel);
        inventory_panel.setLayout(inventory_panelLayout);
        inventory_panelLayout.setHorizontalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        inventory_panelLayout.setVerticalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(inventory_panel, "inventory_imageCard");

        javax.swing.GroupLayout settings_panelLayout = new javax.swing.GroupLayout(settings_panel);
        settings_panel.setLayout(settings_panelLayout);
        settings_panelLayout.setHorizontalGroup(
            settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        settings_panelLayout.setVerticalGroup(
            settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(settings_panel, "setting_cardImage");

        sellersCardImage_panel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout sellersCardImage_panelLayout = new javax.swing.GroupLayout(sellersCardImage_panel);
        sellersCardImage_panel.setLayout(sellersCardImage_panelLayout);
        sellersCardImage_panelLayout.setHorizontalGroup(
            sellersCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        sellersCardImage_panelLayout.setVerticalGroup(
            sellersCardImage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        photo_panel.add(sellersCardImage_panel, "sellers_imagecard");

        sections_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        customers_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customers_btn.setText("العملاء");
        customers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customers_btnActionPerformed(evt);
            }
        });

        sellers_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sellers_btn.setText("المبيع");
        sellers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellers_btnActionPerformed(evt);
            }
        });

        expenes_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        expenes_btn.setText("التحصيل");
        expenes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenes_btnActionPerformed(evt);
            }
        });

        kareemWthdrawals_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kareemWthdrawals_btn.setText("مسحوبات كريم");
        kareemWthdrawals_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kareemWthdrawals_btnActionPerformed(evt);
            }
        });

        kareemWthdrawals_btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kareemWthdrawals_btn1.setText("الفواتير");
        kareemWthdrawals_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kareemWthdrawals_btn1ActionPerformed(evt);
            }
        });

        inventory_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inventory_btn.setText("الجرد");
        inventory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sections_panelLayout = new javax.swing.GroupLayout(sections_panel);
        sections_panel.setLayout(sections_panelLayout);
        sections_panelLayout.setHorizontalGroup(
            sections_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sections_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sections_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expenes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kareemWthdrawals_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kareemWthdrawals_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventory_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sellers_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sections_panelLayout.setVerticalGroup(
            sections_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sections_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sellers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kareemWthdrawals_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kareemWthdrawals_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventory_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(sections_panel);

        fridage_label.setBackground(new java.awt.Color(0, 0, 0));
        fridage_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fridage_label.setForeground(new java.awt.Color(240, 248, 6));
        fridage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fridage_label.setText("jLabel1");
        fridage_label.setOpaque(true);
        fridage_label.setPreferredSize(new java.awt.Dimension(150, 30));

        card_panel.setLayout(new java.awt.CardLayout());

        jMenuBar1.setInheritsPopupMenu(true);

        jMenu1.setText("الإعدادات");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu1.setInheritsPopupMenu(true);

        backUp_MI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backUp_MI.setText("حفظ قاعدة البيانات");
        backUp_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUp_MIActionPerformed(evt);
            }
        });
        jMenu1.add(backUp_MI);

        dailyWork_MI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dailyWork_MI.setText("تسوية اليوم");
        dailyWork_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyWork_MIActionPerformed(evt);
            }
        });
        jMenu1.add(dailyWork_MI);

        changePassword_MI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        changePassword_MI.setText("تغير كلمة المرور");
        changePassword_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassword_MIActionPerformed(evt);
            }
        });
        jMenu1.add(changePassword_MI);

        recovery_MI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        recovery_MI.setText("إسترجاع قاعدة البيانات");
        recovery_MI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recovery_MI.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        recovery_MI.setInheritsPopupMenu(true);
        recovery_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recovery_MIActionPerformed(evt);
            }
        });
        jMenu1.add(recovery_MI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("عرض");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.setInheritsPopupMenu(true);

        archive_MI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        archive_MI.setText("الأرشيف");
        archive_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archive_MIActionPerformed(evt);
            }
        });
        jMenu2.add(archive_MI);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fridage_label, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fridage_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                    .addComponent(card_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellers_btnActionPerformed
        // TODO add your handling code here:
        CardLayout c=(CardLayout)photo_panel.getLayout();
        c.show(photo_panel,"sellers_imagecard");
        
        
          c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"sellers_card");
        sellersPage.refrishPage();
    }//GEN-LAST:event_sellers_btnActionPerformed

    private void customers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customers_btnActionPerformed
        // TODO add your handling code here:
        
        //customers_card
         CardLayout c=(CardLayout)photo_panel.getLayout();
        c.show(photo_panel,"customers_Imagecard");
        
        
           c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"customers_card");
        customersPanel.refrish();
        
    }//GEN-LAST:event_customers_btnActionPerformed

    private void expenes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenes_btnActionPerformed
        // TODO add your handling code here:
        inputOutputtab.refresh();
                  CardLayout c=(CardLayout)photo_panel.getLayout();
        c.show(photo_panel,"expense_imageCard");
        
        
           c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"expense_card");
    }//GEN-LAST:event_expenes_btnActionPerformed

    private void kareemWthdrawals_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kareemWthdrawals_btnActionPerformed
        // TODO add your handling code here:
                   CardLayout c=(CardLayout)photo_panel.getLayout();
        c.show(photo_panel,"kareemWith_imageCard");
        
        
           c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"KareemWithdrawals_card");
    }//GEN-LAST:event_kareemWthdrawals_btnActionPerformed
    String NormalizeinArabic(String str) {

        char[] arabicChars = {'٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'};
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            if (Character.isDigit(str.charAt(i))) {
                builder.append(arabicChars[(int) (str.charAt(i)) - 48]);
            } else {
                builder.append(str.charAt(i));
            }
        }
//        System.out.println("Number in English : " + str);
//        System.out.println("Number In Arabic : " + builder.toString());
        return builder.toString();
    }

    private void kareemWthdrawals_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kareemWthdrawals_btn1ActionPerformed
        // TODO add your handling code here:
        
        
         CardLayout c=(CardLayout)photo_panel.getLayout();
         c.show(photo_panel,"orders_ImageCard");
        
        
           c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"Orders_card");
    }//GEN-LAST:event_kareemWthdrawals_btn1ActionPerformed

    private void inventory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_btnActionPerformed
        // TODO add your handling code here:
        
      CardLayout   c=(CardLayout)card_panel.getLayout();
        c.show(card_panel,"inventory_card");
        c=(CardLayout)photo_panel.getLayout();
        c.show(photo_panel, "inventory_imageCard");
        inventorPage.intiatePage();
        
    }//GEN-LAST:event_inventory_btnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         data_source.logout();
           this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_formWindowClosed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        String fridageName = (this.firdage_id == 1) ? "محل رقم 18" : "محل رقم 21";
        this.fridage_label.setText(NormalizeinArabic(fridageName));
    }//GEN-LAST:event_formFocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String fridageName = (this.firdage_id == 1) ? "محل رقم 18" : "محل رقم 21";
        this.fridage_label.setText(NormalizeinArabic(fridageName));
    }//GEN-LAST:event_formWindowActivated

    private void backUp_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUp_MIActionPerformed
        // TODO add your handling code here:
        
     CardLayout c=(CardLayout)dialgContainer_panel.getLayout();
     c.show(dialgContainer_panel, "backUP");
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_backUp_MIActionPerformed

    private void dailyWork_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyWork_MIActionPerformed
        // TODO add your handling code here:
        CardLayout c=(CardLayout)dialgContainer_panel.getLayout();
     c.show(dialgContainer_panel, "settelement");
     jDialog1.setVisible(true);
    }//GEN-LAST:event_dailyWork_MIActionPerformed

    private void changePassword_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassword_MIActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(true);
    }//GEN-LAST:event_changePassword_MIActionPerformed

    private void recovery_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recovery_MIActionPerformed
         // TODO add your handling code here:
        CardLayout c=(CardLayout)dialgContainer_panel.getLayout();
     c.show(dialgContainer_panel, "recovery");
     jDialog1.setVisible(true);
    }//GEN-LAST:event_recovery_MIActionPerformed

    private void archive_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archive_MIActionPerformed
        // TODO add your handling code here:
     if(!archivedLoaded)
     {
        archive_frame.add(new archive_pkg.Archive(archive_frame, data_source));
    archivedLoaded=true;
     }
            archive_frame.setVisible(true);

    }//GEN-LAST:event_archive_MIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OrderCardImage_panel;
    private javax.swing.JMenuItem archive_MI;
    private javax.swing.JFrame archive_frame;
    private javax.swing.JMenuItem backUp_MI;
    private javax.swing.JPanel card_panel;
    private javax.swing.JMenuItem changePassword_MI;
    private javax.swing.JPanel customersCardImage_panel;
    private javax.swing.JButton customers_btn;
    private javax.swing.JMenuItem dailyWork_MI;
    private javax.swing.JPanel dialgContainer_panel;
    private javax.swing.JButton expenes_btn;
    private javax.swing.JPanel expenes_panel;
    private javax.swing.JLabel fridage_label;
    private javax.swing.JButton inventory_btn;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel kareemWithadralsCardImage_panel;
    private javax.swing.JButton kareemWthdrawals_btn;
    private javax.swing.JButton kareemWthdrawals_btn1;
    private javax.swing.JPanel log_panel;
    private javax.swing.JPanel photo_panel;
    private javax.swing.JMenuItem recovery_MI;
    private javax.swing.JPanel sections_panel;
    private javax.swing.JPanel sellersCardImage_panel;
    private javax.swing.JButton sellers_btn;
    private javax.swing.JPanel settings_panel;
    // End of variables declaration//GEN-END:variables
}
