/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import javax.swing.JFrame;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author ahmed
 */
public class Orders extends javax.swing.JPanel {

    /**
     * Creates new form Orders
     */  Main_Frame myFrame;
    DataSourc data_source ;
    public Orders(Main_Frame myFrame,DataSourc data_source) {
         this.myFrame=myFrame;
        this.data_source=data_source;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new EditingOrders_panel1(myFrame, data_source);
        jPanel2 = new BillsDelivery1(myFrame, data_source);
        jPanel3 = new OrderArchived(myFrame, data_source);

        setLayout(new javax.swing.OverlayLayout(this));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTabbedPane1.addTab("تحرير الفواتير", jPanel1);
        jTabbedPane1.addTab("تسليم الفواتير", jPanel2);
        jTabbedPane1.addTab("ارشيف", jPanel3);

        add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("تسليم الفواتير");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
