/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import shop.data_source_pkg.DataSourc;

/**
 *
 * @author ahmed
 */
public class Sellers_panel extends javax.swing.JPanel {

    /**
     * Creates new form Sellers_panel
     */
    DailySales DailySales_tab;
    Loans Loans_tab;
    LoanArchive LoanArchive_tab;
    EditeSellerOrder  EditeSellerOrder_tab;
    Main_Frame myFrame;
    DataSourc data_source;

    public Sellers_panel(Main_Frame myFrame, DataSourc data_source) {
        this.data_source = data_source;
        this.myFrame = myFrame;
        
        DailySales_tab = new DailySales(myFrame, data_source);
        Loans_tab = new Loans(myFrame, data_source);
        LoanArchive_tab = new LoanArchive(myFrame, data_source);
        EditeSellerOrder_tab=new EditeSellerOrder(myFrame, data_source);
        
        
        initComponents();
        jPanel1.add(DailySales_tab);
        jPanel2.add(Loans_tab);
        jPanel3.add(LoanArchive_tab);
        jPanel4.add(EditeSellerOrder_tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new DailySales(myFrame,data_source);
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new javax.swing.OverlayLayout(this));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));
        jTabbedPane1.addTab("المبيع اليومي", jPanel1);

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));
        jTabbedPane1.addTab("الزمامات", jPanel2);

        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));
        jTabbedPane1.addTab("ارشيف الزمامات", jPanel3);

        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));
        jTabbedPane1.addTab("التعديل", jPanel4);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    public void refrishPage() {
       DailySales_tab.fillDailySalesbookDates();
       Loans_tab.intiatePage();
       

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
