/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.GUI;

import java.awt.CardLayout;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import shop.Validation_pkg.DoubleInputValidator;
import shop.data_source_pkg.DataSourc;
import  shop.GUI_attachement_pkg.*;
import shop.data_structures_pkg.Pair;


/**
 *
 * @author Compu City
 */
public class shopLoans extends javax.swing.JPanel {
    /**
     * Creates new form shopLoans
     */
    Main_Frame myFrame;
    DataSourc data_source;
    public shopLoans( Main_Frame myFrame, DataSourc data_source) {
        this.data_source=data_source;
        this.myFrame=myFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        in_RB = new javax.swing.JRadioButton();
        out_RB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        total_TF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        intLoan_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        incomeDatainput_panel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        inAmount_TF = new javax.swing.JTextField();
        paid_label1 = new javax.swing.JLabel();
        report_panel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inNotes_TA = new javax.swing.JTextArea();
        intSave_btn = new javax.swing.JButton();
        inWraning_label = new javax.swing.JLabel();
        inName_TF = new PersonName_STF(myFrame, "IN_LOAN", data_source);
        jScrollPane6 = new javax.swing.JScrollPane();
        in_Table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        inInst_table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        inDet_table = new javax.swing.JTable();
        outLoan_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        incomeDatainput_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        OUTAmount_TF = new javax.swing.JTextField();
        paid_label = new javax.swing.JLabel();
        report_panel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outNotes_TA = new javax.swing.JTextArea();
        outSave_btn = new javax.swing.JButton();
        outWraning_label = new javax.swing.JLabel();
        oUTName_TF = new PersonName_STF(myFrame, "OUT_LOAN", data_source);
        jScrollPane1 = new javax.swing.JScrollPane();
        out_table = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        outInst_table = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        outDet_table = new javax.swing.JTable();

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true));

        buttonGroup1.add(in_RB);
        in_RB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        in_RB.setSelected(true);
        in_RB.setText("مديونية الداخل");
        in_RB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        in_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_RBActionPerformed(evt);
            }
        });

        buttonGroup1.add(out_RB);
        out_RB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        out_RB.setText("مدونية الخارج");
        out_RB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        out_RB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        out_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_RBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("صافي المديونية:");

        total_TF.setEditable(false);
        total_TF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_RB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(out_RB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(in_RB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(out_RB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        incomeDatainput_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 165, 46), 3, true), "بيانات الداخل", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("الأسم:");

        inAmount_TF.setFont(new java.awt.Font("B Fantezy", 0, 20)); // NOI18N
        inAmount_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        paid_label1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        paid_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paid_label1.setText("المبلغ:");

        report_panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ملاحظات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        report_panel2.setLayout(new javax.swing.OverlayLayout(report_panel2));

        jScrollPane5.setWheelScrollingEnabled(false);

        inNotes_TA.setColumns(20);
        inNotes_TA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inNotes_TA.setLineWrap(true);
        inNotes_TA.setRows(5);
        inNotes_TA.setToolTipText("ملاحظات");
        inNotes_TA.setWrapStyleWord(true);
        inNotes_TA.setBorder(null);
        jScrollPane5.setViewportView(inNotes_TA);

        report_panel2.add(jScrollPane5);

        intSave_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        intSave_btn.setText("حفظ");
        intSave_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intSave_btnActionPerformed(evt);
            }
        });

        inWraning_label.setBackground(new java.awt.Color(204, 204, 255));
        inWraning_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        inWraning_label.setForeground(new java.awt.Color(255, 0, 51));
        inWraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        inName_TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout incomeDatainput_panel1Layout = new javax.swing.GroupLayout(incomeDatainput_panel1);
        incomeDatainput_panel1.setLayout(incomeDatainput_panel1Layout);
        incomeDatainput_panel1Layout.setHorizontalGroup(
            incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report_panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panel1Layout.createSequentialGroup()
                        .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inAmount_TF)
                            .addComponent(inName_TF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paid_label1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panel1Layout.createSequentialGroup()
                        .addComponent(inWraning_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intSave_btn)))
                .addContainerGap())
        );
        incomeDatainput_panel1Layout.setVerticalGroup(
            incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inAmount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paid_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(report_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intSave_btn)
                    .addComponent(inWraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PlainDocument inAmount_TF_doc = (PlainDocument)inAmount_TF.getDocument();
        inAmount_TF_doc.setDocumentFilter(new DoubleInputValidator(this.inAmount_TF , this.inWraning_label));

        in_Table.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        in_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "المبلغ ", "الاسم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        in_Table.setRowHeight(25);
        in_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_TableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(in_Table);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(incomeDatainput_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incomeDatainput_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jSplitPane1.setDividerLocation(400);

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 161, 10), 2, true), "الأقساط المدفوعة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jScrollPane7.setPreferredSize(new java.awt.Dimension(462, 150));

        inInst_table.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        inInst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ملاحظات", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inInst_table.setRowHeight(30);
        jScrollPane7.setViewportView(inInst_table);

        jSplitPane1.setLeftComponent(jScrollPane7);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true), "المبالغ المقترضة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jScrollPane4.setPreferredSize(new java.awt.Dimension(462, 150));

        inDet_table.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        inDet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الملاحظات", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inDet_table.setRowHeight(30);
        jScrollPane4.setViewportView(inDet_table);

        jSplitPane1.setRightComponent(jScrollPane4);

        jPanel4.add(jSplitPane1);

        javax.swing.GroupLayout intLoan_panelLayout = new javax.swing.GroupLayout(intLoan_panel);
        intLoan_panel.setLayout(intLoan_panelLayout);
        intLoan_panelLayout.setHorizontalGroup(
            intLoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intLoan_panelLayout.createSequentialGroup()
                .addGroup(intLoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        intLoan_panelLayout.setVerticalGroup(
            intLoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intLoan_panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.add(intLoan_panel, "inLoan_card");

        incomeDatainput_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true), "بيانات الخارج", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("الأسم:");

        OUTAmount_TF.setFont(new java.awt.Font("B Fantezy", 0, 20)); // NOI18N
        OUTAmount_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        paid_label.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        paid_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paid_label.setText("المبلغ:");

        report_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ملاحظات", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        report_panel1.setLayout(new javax.swing.OverlayLayout(report_panel1));

        jScrollPane3.setWheelScrollingEnabled(false);

        outNotes_TA.setColumns(20);
        outNotes_TA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        outNotes_TA.setLineWrap(true);
        outNotes_TA.setRows(5);
        outNotes_TA.setToolTipText("ملاحظات");
        outNotes_TA.setWrapStyleWord(true);
        outNotes_TA.setBorder(null);
        jScrollPane3.setViewportView(outNotes_TA);

        report_panel1.add(jScrollPane3);

        outSave_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        outSave_btn.setText("حفظ");
        outSave_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outSave_btnActionPerformed(evt);
            }
        });

        outWraning_label.setBackground(new java.awt.Color(204, 204, 255));
        outWraning_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        outWraning_label.setForeground(new java.awt.Color(255, 0, 51));
        outWraning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        oUTName_TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oUTName_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout incomeDatainput_panelLayout = new javax.swing.GroupLayout(incomeDatainput_panel);
        incomeDatainput_panel.setLayout(incomeDatainput_panelLayout);
        incomeDatainput_panelLayout.setHorizontalGroup(
            incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report_panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panelLayout.createSequentialGroup()
                        .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OUTAmount_TF)
                            .addComponent(oUTName_TF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paid_label, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeDatainput_panelLayout.createSequentialGroup()
                        .addComponent(outWraning_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outSave_btn)))
                .addContainerGap())
        );
        incomeDatainput_panelLayout.setVerticalGroup(
            incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeDatainput_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OUTAmount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oUTName_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(report_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeDatainput_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outSave_btn)
                    .addComponent(outWraning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PlainDocument OUTAmount_TF_doc = (PlainDocument)OUTAmount_TF.getDocument();
        OUTAmount_TF_doc.setDocumentFilter(new DoubleInputValidator(this.OUTAmount_TF , this.outWraning_label));

        out_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        out_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "المبلغ ", "الاسم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        out_table.setRowHeight(25);
        out_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                out_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(out_table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(incomeDatainput_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addComponent(incomeDatainput_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        jSplitPane2.setDividerLocation(400);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 159, 19), 2, true), "الأقساط المدفوعة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(462, 150));

        outInst_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        outInst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الملاحظات", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outInst_table.setRowHeight(30);
        jScrollPane2.setViewportView(outInst_table);

        jSplitPane2.setLeftComponent(jScrollPane2);

        jScrollPane8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true), "المبالغ المقترضة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jScrollPane8.setPreferredSize(new java.awt.Dimension(462, 150));

        outDet_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        outDet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الملاحظات", "المبلغ", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outDet_table.setRowHeight(30);
        jScrollPane8.setViewportView(outDet_table);

        jSplitPane2.setRightComponent(jScrollPane8);

        jPanel6.add(jSplitPane2);

        javax.swing.GroupLayout outLoan_panelLayout = new javax.swing.GroupLayout(outLoan_panel);
        outLoan_panel.setLayout(outLoan_panelLayout);
        outLoan_panelLayout.setHorizontalGroup(
            outLoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        outLoan_panelLayout.setVerticalGroup(
            outLoan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outLoan_panelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        jPanel2.add(outLoan_panel, "outLoan_card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    boolean validateOut_loan(){
    
    String name=oUTName_TF.getText() ;
    String amount =OUTAmount_TF.getText();
    if(name.isEmpty()){
    this.outWraning_label.setText("يجب إدخال الأسم");
    return false;
    
    
     }
    else if (amount.isEmpty()){
    
    
     this.outWraning_label.setText("يجب إدخال المبلغ");
    return false;
    
    }
    double d_amount =Double.parseDouble(amount);
    
    if(!data_source.vallidateSafeWithdrawal(d_amount)){return false;}
    Pair<Double,String> p=data_source.getLoanerAmount_type(name);
    
    if(p.getSecond().equals("IN_LOAN")){
    
      this.outWraning_label.setText("يجب سداد مبلغ  "+p.getFrist()+"لصالح هذا العميل اولا");
    return false;
    
    
    }
    else{
    
     this.outWraning_label.setText("");
    return true;
    
    }
    
    
     }
    
    
     boolean validatein_loan(){
    
    String name=inName_TF.getText() ;
    String amount =inAmount_TF.getText();
    if(name.isEmpty()){
    this.inWraning_label.setText("يجب إدخال الأسم");
    return false;
    
    
     }
    else if (amount.isEmpty()){
    
    
     this.inWraning_label.setText("يجب إدخال المبلغ");
    return false;
    
    }
    double d_amount =Double.parseDouble(amount);
    Pair<Double,String> p=data_source.getLoanerAmount_type(name);
    
    if(p.getSecond().equals("OUT_LOAN")){
    
      this.outWraning_label.setText("يجب تحصيل مبلغ "+p.getFrist()+"من هذا العميل اولا");
    return false;
    
    
    }
    else{
    
     this.outWraning_label.setText("");
    return true;
    
    }
    
    
     }
     String NormalizeinArabic(String str) {

        char[] arabicChars = {'٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'};
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            if (Character.isDigit(str.charAt(i))) {
                builder.append(arabicChars[(int) (str.charAt(i)) - 48]);
            } else {
                builder.append(str.charAt(i));
            }
        }
//        System.out.println("Number in English : " + str);
//        System.out.println("Number In Arabic : " + builder.toString());
        return builder.toString();
    }

void intiateInLoanPage(){
    this. inAmount_TF.setText("");
    this.inName_TF.setText("");
    this.inWraning_label.setText("");
    
    Vector<Object>data=data_source.getLoaners("IN_LOAN");
    DefaultTableModel dtm=(DefaultTableModel)in_Table.getModel();
    dtm.setDataVector(data, loaner_columnTitles);
    double amount =data_source.loanbalance("IN_LOAN");
        this.total_TF.setText(NormalizeinArabic(String.valueOf(amount)));
    
    in_Table.setModel(dtm);
    
    
    
}   
  void intiateOutLoanPage(){
    this. OUTAmount_TF.setText("");
    this.oUTName_TF.setText("");
    this.outWraning_label.setText("");
    
    Vector<Object>data=data_source.getLoaners("OUT_LOAN");
    DefaultTableModel dtm=(DefaultTableModel)out_table.getModel();
    dtm.setDataVector(data, loaner_columnTitles);
    
     double amount =data_source.loanbalance("OUT_LOAN");
        this.total_TF.setText(NormalizeinArabic(String.valueOf(amount)));
    out_table.setModel(dtm);
    
    
    
}   
    
      
    
    
    
    private void outSave_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outSave_btnActionPerformed
        // TODO add your handling code here:
      
        if(validateOut_loan()){
        double amount = Double.parseDouble(OUTAmount_TF.getText());
       String name =oUTName_TF.getText();
       String notes =outNotes_TA.getText();
       

        data_source.loanIncTransaction(amount, name, notes,"OUT_LOAN",myFrame.firdage_id);
        
         amount =data_source.loanbalance("OUT_LOAN");
        this.total_TF.setText(String.valueOf(amount));
        intiateOutLoanPage();
        
        
        }
       // outintiateInPage();}
    }//GEN-LAST:event_outSave_btnActionPerformed

    private void intSave_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intSave_btnActionPerformed
        // TODO add your handling code here:
        
        if(validatein_loan()){
          double amount = Double.parseDouble(inAmount_TF.getText());
       String name =inName_TF.getText();
       String notes =inNotes_TA.getText();
       

        data_source.loanIncTransaction(amount, name, notes,"IN_LOAN",myFrame.firdage_id);
         
        intiateInLoanPage();
        
        }
    }//GEN-LAST:event_intSave_btnActionPerformed

    private void in_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_TableMouseClicked
        // TODO add your handling code here:
        
        
        int index =in_Table.getSelectedRow();
       String name =in_Table.getModel().getValueAt(index, 1).toString();
       
        Vector<Object>data=data_source.getLoanerDetail(name,"IN_LOAN");
    DefaultTableModel dtm=(DefaultTableModel)inDet_table.getModel();
    dtm.setDataVector(data, loanersDetail);
        
    inDet_table.setModel(dtm);
    
       
    
    
    
         data=data_source.getLoanerInst(name,"IN_LOAN");
     dtm=(DefaultTableModel)inInst_table.getModel();
    dtm.setDataVector(data, loanersDetail);
        
    inInst_table.setModel(dtm);
    
    
    
    
    }//GEN-LAST:event_in_TableMouseClicked

    private void out_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_tableMouseClicked
        // TODO add your handling code here:
        
           int index =out_table.getSelectedRow();
       String name =out_table.getModel().getValueAt(index, 1).toString();
       
        Vector<Object>data=data_source.getLoanerDetail(name,"OUT_LOAN");
    DefaultTableModel dtm=(DefaultTableModel)outDet_table.getModel();
    dtm.setDataVector(data, loanersDetail);
        
    outDet_table.setModel(dtm);
    
       
    
    
    
         data=data_source.getLoanerInst(name,"OUT_LOAN");
     dtm=(DefaultTableModel)outInst_table.getModel();
    dtm.setDataVector(data, loanersDetail);
        
    outInst_table.setModel(dtm); 
        
        
        
    }//GEN-LAST:event_out_tableMouseClicked

    private void out_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_RBActionPerformed
        // TODO add your handling code here:
             if(out_RB.isSelected())
        {
        
            CardLayout c=(CardLayout)jPanel2.getLayout();
            c.show(jPanel2,"outLoan_card");
             intiateOutLoanPage();
        
        }
       
        
        
    }//GEN-LAST:event_out_RBActionPerformed

    private void in_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_RBActionPerformed
        // TODO add your handling code here:
        
         if(in_RB.isSelected())
        {
        //inLoan_card
            CardLayout c=(CardLayout)jPanel2.getLayout();
            c.show(jPanel2,"inLoan_card");
             intiateInLoanPage();
        
        }
        
      
        
    }//GEN-LAST:event_in_RBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OUTAmount_TF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inAmount_TF;
    private javax.swing.JTable inDet_table;
    private javax.swing.JTable inInst_table;
    private javax.swing.JTextField inName_TF;
    private javax.swing.JTextArea inNotes_TA;
    private javax.swing.JLabel inWraning_label;
    private javax.swing.JRadioButton in_RB;
    private javax.swing.JTable in_Table;
    private javax.swing.JPanel incomeDatainput_panel;
    private javax.swing.JPanel incomeDatainput_panel1;
    private javax.swing.JPanel intLoan_panel;
    private javax.swing.JButton intSave_btn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField oUTName_TF;
    private javax.swing.JTable outDet_table;
    private javax.swing.JTable outInst_table;
    private javax.swing.JPanel outLoan_panel;
    private javax.swing.JTextArea outNotes_TA;
    private javax.swing.JButton outSave_btn;
    private javax.swing.JLabel outWraning_label;
    private javax.swing.JRadioButton out_RB;
    private javax.swing.JTable out_table;
    private javax.swing.JLabel paid_label;
    private javax.swing.JLabel paid_label1;
    private javax.swing.JPanel report_panel1;
    private javax.swing.JPanel report_panel2;
    private javax.swing.JTextField total_TF;
    // End of variables declaration//GEN-END:variables

Vector<String> loaner_columnTitles=new Vector<>(Arrays.asList( "المبلغ ", "الاسم"));
Vector<String> loanersDetail=new Vector<>(Arrays.asList("الملاحظات", "المبلغ", "التاريخ"));



}
